Dropdown PR Feedback
mozilla/foundation.mozilla.org pull request #10058
Opened 2023-01-26 21:28 UTC by fessehaye

Removed extra tailwind class.
Dropdown now adjust width when the dropdown is open, so the `Sort By` Text should always be visible

2023-01-26 22:58 UTC, mmmavis commented
@fessehaye is this for ticket #9870 ? Could you point me to where Nancy's feedback is so I can QA this PR accordingly? Thanks!

2023-01-27 00:21 UTC, fessehaye commented
https://github.com/mozilla/foundation.mozilla.org/issues/9870#issuecomment-1405793683

2023-01-27 02:54 UTC, fessehaye commented
https://github.com/mozilla/foundation.mozilla.org/pull/9999#issuecomment-1397760495

2023-01-27 17:37 UTC, mmmavis requested changes
I've found some issues

- Arrow in dropdown overlaps with the option text on certain screen sizes
- Dropdown option text can still get cut off on smaller screen
- Jumping dropdown label when dropdown is expanded. See screen recording 00:00-0:03 and 00:15-00:17

Let's chat with design and consider a more all-locale friendly design approach. I'm thinking having a fixed width dropdown and let the dropdown option text auto wrap into multiple lines when the text is long. This way the layout is consistent across all locales. I would like to borrow design team's expertise and have them weigh in! /cc @nancyt1 

https://user-images.githubusercontent.com/2896608/215152850-f0d0b565-3cda-40f2-ba1f-e652ac3d13c4.mov

2023-01-27 18:05 UTC, nancyt1 commented
@mmmavis I think some of this was fixed in daniel's ticket #9871 but yes a conversation would be good, this is getting complicated lol

2023-01-30 23:37 UTC, fessehaye commented
Due to some reverts, I will close this PR and add you two to a meeting about this tmrw. Thx!

2023-01-30 23:37 UTC, closed without merging