Implement hreflang via HTTP headers
mozilla/foundation.mozilla.org pull request #5062
Opened 2020-08-17 14:14 UTC by TheoChevalier

Closes #5049

Links localized pages in each page metadata so that the localized pages have better changes of ranking in Google

2020-09-14 23:20 UTC, Pomax requested changes
essentially R+ but let's remove the rogue print

2020-09-14 23:20 UTC, Pomax commented on network-api/networkapi/context_processor.py
> +    print(re.sub(r'^/' + lang, '', url))
let's take this line out =)

2020-09-16 10:05 UTC, TheoChevalier commented on network-api/networkapi/context_processor.py
> +    print(re.sub(r'^/' + lang, '', url))
woops! :) Thank you

2020-09-16 18:15 UTC, Pomax approved these changes

2020-09-16 18:27 UTC, merged