add redirects to who-we-are and what-you-can-do
mozilla/foundation.mozilla.org pull request #5171
Opened 2020-09-02 21:08 UTC by cadecairos

Closes #5144 

Add two localized redirects to networkapi/urls.py:

`/[locale/]about/` -> `/[locale/]who-we-are`
`[locale/]participate` -> `/[locale/]what-we-do`

2020-09-08 15:30 UTC, KalobTaulien approved these changes
Tested, works as expected. 👍

2020-09-08 23:22 UTC, Pomax requested changes
Is there a way for us to do this in a similar way to i18n_patterns? E.g. `urlpatterns = moforedirected(urlpatterns )` before `urlpatterns 
 += i18n_patterns(...)`, so we're not spreading the locations over multiple files?

2020-09-09 18:58 UTC, cadecairos commented
> Is there a way for us to do this in a similar way to i18n_patterns? E.g. `urlpatterns = moforedirection(urlpatterns)` before `urlpatterns += i18n_patterns(...)`, so we're not spreading the locations over multiple files?

The URL patterns are wrapped in `i18n_patterns(...)` already, so that the route handlers are applied to all locales handled by Django. Can you elaborate some more on what you envision for this?

2020-09-10 17:47 UTC, Pomax commented
I mean "let's make this something we have in a single file, and that can be added in urls.py as one-liner", e.g.:

```
...
from .redirects import mofo_redirects
...

# Custom routes
patterns = [
    # Buyer's Guide / Privacy Not Included
    url(r'^privacynotincluded/', include('networkapi.buyersguide.urls')),

    # Blog RSS feed
    path('blog/rss/', RSSFeed()),
    path('blog/atom/', AtomFeed())
]

# top-level redirects
pattens += mofo_redirects

# wagtail-managed data
patterns.append(url(r'', include(wagtail_urls)))

# Anything that needs to respect the localised
# url format with /<language_code>/ infixed needs
# to be wrapped by django's i18n_patterns feature:
urlpatterns += i18n_patterns(patterns)

...
```

So that we can update redirects in the one file that is intuitively the file where redirects are housed.

2020-09-10 17:51 UTC, Pomax commented on network-api/networkapi/wagtailpages/views.py
> +def redirect_to_whoweare(request, subpath):
It feels like this code should just be directly used in the redirect pattern file, e.g.
```
 url(r'^about/(?P<subpath>.*)', lambda req, path: localized_redirect(req, path, 'who-we-are')),
```

2020-09-10 20:04 UTC, Pomax commented on network-api/networkapi/urls.py
> +    *foundation_redirects(),
sneeeeeaky

2020-09-10 20:05 UTC, Pomax commented on network-api/networkapi/wagtailpages/views.py
> +    return redirect(f'/{request.LANGUAGE_CODE}/{destination_path}/{subpath}{query_string}')
👍

2020-09-10 20:32 UTC, Pomax approved these changes

2020-09-14 15:58 UTC, merged