Use random.choice instead of database random ordering
mozilla/foundation.mozilla.org pull request #5212
Opened 2020-09-10 21:12 UTC by Pomax

Closes #5202

This should make Percy stable again, replacing all left-over `order_by("?")`, which is a database level randomization, with Python's `random.choice`, which respects our seed values.

2020-09-10 21:51 UTC, mmmavis requested changes
Thanks for the explanation regarding `order_by("?")` vs `random.choice`.

Code looks good! Looks like there's one more place we need to update -- in `homepage_features.py`

```py
home_page.spotlight_posts = [
        HomepageSpotlightPosts.objects.create(
            page=home_page,
            blog=BlogPage.objects.order_by("?").first()
        )
        for i in range(NUM_SPOTLIGHT_POSTS)
    ]
```

2020-09-10 22:41 UTC, Pomax commented
That's already in the PR though, https://github.com/mozilla/foundation.mozilla.org/pull/5212/files#diff-608a11ec663c53b9ff8711ab42768fc8R47 ?

2020-09-10 22:43 UTC, mmmavis approved these changes
My bad. Ignore what I said earlier regarding fixing one more place. I think I had too many tabs open and probably was on a wrong branch when i checked the code lol.

2020-09-15 15:38 UTC, cadecairos approved these changes

2020-09-15 15:48 UTC, merged