Add GA event trackings to homepage
mozilla/foundation.mozilla.org pull request #5219
Opened 2020-09-14 19:36 UTC by mmmavis

Closes #5048

2020-09-15 14:48 UTC, taisdesouzalessa commented
@mmmavis I tried to QA here but I am not sure I can follow if it is right. I may need some support here on how to QA this properly. Would you give me a hand after stand up today? Thanks!

2020-09-15 19:10 UTC, taisdesouzalessa approved these changes
all good and working as expected. Thanks for the tutorial, Mavis!

2020-09-15 20:42 UTC, Pomax requested changes

2020-09-15 20:42 UTC, Pomax commented on network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/take_action.html
> +            data-form-position="body"
This change turns the "Take action" callout from this:

![image](https://user-images.githubusercontent.com/177243/93262565-4c271080-f759-11ea-9eb0-cf4d27912864.png)

Into this:

![image](https://user-images.githubusercontent.com/177243/93262591-56490f00-f759-11ea-9c85-be1cdb02a352.png)

2020-09-16 01:34 UTC, Pomax approved these changes

2020-09-16 01:45 UTC, merged