[5170] Article Page FActories
mozilla/foundation.mozilla.org pull request #5281
Opened 2020-09-22 18:35 UTC by KalobTaulien

Closes #5170 
Related PRs/issues #5170 

## Checklist

**Changes in Models:**
- [x] Did I update or add new fake data?

**Other:**
I've patched the .rich-text "issue" from Wagtail 2.10 where `.rich-text` is removed from the frontend output. I made our beautiful soup and scss match this to fix the styling of the Article Pages.

2020-09-22 20:24 UTC, Pomax requested changes
minor changes, otherwise this looks R+

2020-09-22 20:24 UTC, Pomax commented on network-api/networkapi/utility/faker/streamfield_provider.py
> +    value = ' '.join(fake.words(nb=10))
```suggestion
    value = Faker('sentence', nb_words=10)
```

2020-09-23 16:01 UTC, KalobTaulien commented
@Pomax I fixed up those suggestions. As a note, there's a few more in that file that use `' '.join(...)` but I only tackled the ones related to this PR.

2020-09-23 18:07 UTC, Pomax approved these changes

2020-09-23 18:11 UTC, merged