[5255] Add & remove criteria from product page template
mozilla/foundation.mozilla.org pull request #5295
Opened 2020-09-23 20:04 UTC by KalobTaulien

Closes #5255 
Related PRs/issues #5255

Related PR: #5280 — I was working off of this PR to reflect the backend changes.

**Notes**:
* I did not add any styling or images. There are TODO comments in here for the next tickets to look at. 
* I copied pre-existing styles (ie `h2.h3-heading`) to keep things similar to how they were before to make the "cleanup" ticket easier to work with. 
* [This is the design](https://app.abstract.com/projects/fa246750-1c19-11e8-b2bf-9db5acc6ed5d/branches/master/commits/4b6da88b41a28a4c1cbbee0f502fa17fe960e90d/files/DBF82218-05B7-47F9-AD7C-8ABDFD109060/layers/BB7D4F2B-6519-45AE-B80F-A70F4F3ECCE9?mode=design&selected=root-BA5F9C19-8B69-4496-9CD1-8E115DD916BC) page I was going off of.

2020-09-23 23:38 UTC, mmmavis reviewed
Hey @KalobTaulien , mind providing a review link? I visited a random product page https://foundation-s-5255-add-r-axgveh.herokuapp.com/en/privacynotincluded/products/percy-cypress/ but it didn't seem to include todos mentioned in the ticket

![image](https://user-images.githubusercontent.com/2896608/94084739-1f0ed980-fdbb-11ea-9669-610731c32d50.png)

2020-09-28 19:34 UTC, KalobTaulien commented
Hey @mmmavis the TODOs are in django template comments. Should be able to see them in the template source

2020-09-28 20:06 UTC, Pomax requested changes

2020-09-28 20:06 UTC, Pomax commented on network-api/networkapi/buyersguide/templates/product_page.html
> +          {% endif %}
These are not boolean values.
```suggestion
          {% include "fragments/signup_requirement.html" with title=email                 value=product.signup_with_email          %}
          {% include "fragments/signup_requirement.html" with title=phone                 value=product.signup_with_phone          %}
          {% include "fragments/signup_requirement.html" with title=third_party_account   value=product.signup_with_third_party    %}
```

2020-09-28 20:54 UTC, Pomax requested changes

2020-09-28 20:54 UTC, Pomax commented on network-api/networkapi/buyersguide/templates/product_page.html
> +            {% if product.meets_minimum_security_standards %}Yes{% else %}No{% endif %}
```suggestion
            {% if product.meets_minimum_security_standards %}
              {% trans "Yes" %}
            {% else %}
              {% trans "No" %}
            {% endif %}
```

2020-09-28 21:08 UTC, Pomax approved these changes

2020-09-28 21:38 UTC, mmmavis approved these changes

2020-09-28 21:45 UTC, kristinashu commented
Is there a new ticket for the work that didn't get done in this ticket #5255? I don't want to loose things like "If the answer to the first AI questions is `No` then the other two questions should be hidden"

2020-09-28 21:47 UTC, Pomax commented
updated the original post so that merging won't close that issue, and updated the issue so that the "field work" and the "styling work" are separate checkboxes.

2020-09-28 21:50 UTC, merged