Add wifi & bluebooth info & add a type.scss for PNI
mozilla/foundation.mozilla.org pull request #5307
Opened 2020-09-24 22:31 UTC by mmmavis

Closes #5249

2020-09-24 23:11 UTC, Pomax requested changes

2020-09-24 23:11 UTC, Pomax commented on network-api/networkapi/buyersguide/templates/product_page.html
> +              <div class="connectivity-requirement use-wifi pni-product-intro-large">{% trans "WiFi" %}</div>
Can we make them `<span>` or `<p>` instead, since they are text elements?

2020-09-24 23:15 UTC, kristinashu commented
Nice, the icons are appearing as expected in all the different possible states. But for design could you please:

- [ ] Add the `-` between `Wi-Fi` (according to Theo this is more common in other languages)
- [ ] Vertically center the icons and the text (in the PR it looks like they are aligned at the bottom but in the design their centers align)  

<img width="244" alt="image" src="https://user-images.githubusercontent.com/1068783/94209226-a1ad9c80-fe80-11ea-8922-30dd9f3a29c4.png">

2020-09-24 23:15 UTC, kristinashu requested changes
See comment.

2020-09-25 16:32 UTC, mmmavis commented
PR updated!

2020-09-25 16:36 UTC, kristinashu approved these changes
Nice!

2020-09-25 17:06 UTC, Pomax approved these changes

2020-09-25 17:06 UTC, merged