Add 'Careers' footer link
mozilla/foundation.mozilla.org pull request #5350
Opened 2020-09-30 17:41 UTC by mmmavis

Closes #5174

2020-09-30 18:20 UTC, taisdesouzalessa approved these changes
All good! Thanks, Mavis :)

2020-09-30 20:47 UTC, Pomax requested changes

2020-09-30 20:47 UTC, Pomax commented on network-api/networkapi/mozfest/templates/partials/mozfest_footer.html
> +  <li><a href="https://careers.mozilla.org/listings/?team=Mozilla%20Foundation" target="_blank" class="dark-theme">{% trans "Careers" %}</a></li>
Let's not add `target="_blank"` if the other links don't use that either

2020-09-30 20:47 UTC, Pomax commented on network-api/networkapi/templates/partials/footer.html
> +                <li><a href="https://careers.mozilla.org/listings/?team=Mozilla%20Foundation" target="_blank" class="dark-theme">{% trans "Careers" %}</a></li>
Let's not add `target="_blank"` if the other links don't use that either

2020-10-01 17:10 UTC, Pomax approved these changes

2020-10-01 20:26 UTC, merged