(WIP) Clean up criteria sections template code and styling
mozilla/foundation.mozilla.org pull request #5365
Opened 2020-10-01 16:24 UTC by mmmavis

Closes #5255

2020-10-01 20:33 UTC, Pomax requested changes
Most looks good, but we can probably remove some of the superfluous whitespacing now, and some minor improvements.

2020-10-01 20:33 UTC, Pomax commented on network-api/networkapi/buyersguide/templates/product_page.html
> +                {% include "fragments/signup_requirement.html" with title=social_data_collected     value=product.social_data_collected    %}
some extra spaces at the end of these.

2020-10-01 21:58 UTC, mmmavis commented on network-api/networkapi/buyersguide/templates/product_page.html
> +
i can reduce them to just one new line in between but readibility wise it wont do much 🤔

2020-10-01 23:09 UTC, mmmavis commented on network-api/networkapi/buyersguide/templates/product_page.html
> +          {% include "fragments/product_criterion.html"  with  label=how_does_it_use_data_collected  value=product.how_does_it_use_data_collected   help="" %}
oh yea forgot to update these

2020-10-01 23:17 UTC, mmmavis commented on network-api/networkapi/buyersguide/templates/product_page.html
> +
Okay I reduced them from 3 new lines to 2 lol

2020-10-01 23:43 UTC, mmmavis commented on network-api/networkapi/buyersguide/templates/product_page.html
> +            {% include "fragments/product_privacy.html"    with  label=privacy_policy_links         value=""                                           links=product.privacy_policy_links
done

2020-10-02 16:17 UTC, Pomax approved these changes
Looks good enough to merge in to me!

2020-10-02 16:25 UTC, kristinashu commented
Not blockers so these could be done as a follow up. Also, @sabrinang can you please confirm that these are correct before Mavis does the updates?

## Styling update requests

- [ ] "What data does it collect?" needs an "?"

_Screen caps from PR_
<img width="263" alt="Screen Shot 2020-10-02 at 8 51 42 AM" src="https://user-images.githubusercontent.com/1068783/94945035-f0fe5900-048e-11eb-84f0-99d3d4214ee2.png">

- [ ] Reduce vertical space between "Camera" and "Device" (and the other places that use this spacing)

_Screen caps from PR_
<img width="546" alt="image" src="https://user-images.githubusercontent.com/1068783/94945620-cd87de00-048f-11eb-8060-325afeec4bad.png">

- [ ] IA help text should be regular, not italic

_Screen caps from PR_
<img width="489" alt="Screen Shot 2020-10-02 at 8 53 00 AM" src="https://user-images.githubusercontent.com/1068783/94945038-f196ef80-048e-11eb-8211-1e84b2b04aa9.png">

- [ ] Contact info should be black with underline and turn to blue/purple with underline on hover (like on prod)

_Screen caps from PR_
<img width="781" alt="Screen Shot 2020-10-02 at 8 54 29 AM" src="https://user-images.githubusercontent.com/1068783/94945041-f22f8600-048e-11eb-9557-41ad9cf30e56.png">

2020-10-02 22:08 UTC, sabrinang commented
@kristinashu @mmmavis  re: comment

**What data does it collect?**
+1 add ?

**Spacing** 
In the comps I had answers 12px below questions/heading because Jen wanted that separation below to make the answer more obvious when help text was present. So it was made the same for all sections including this 3-col style one but should this be reduced everywhere? (I see it does feel far apart)

**Text in AI section**
+1 This text isn’t the last sections “help text” but rather text for all three overall AI questions. That is why it is regular and a bit further then the usual “help text” (it is similar so I can see the confusion)

**Contact links**
 +1 like on prod

2020-10-02 22:33 UTC, mmmavis commented
@kristinashu this is ready for re-review!

I am gonna file a new ticket to make sure we are displaying criteria correctly for the software products as it requires quite a bit of the code changes and I don't want it to be a blocker.

2020-10-02 22:59 UTC, kristinashu approved these changes
Product page looks good!

2020-10-02 23:05 UTC, merged