Fix admin checkboxes
mozilla/foundation.mozilla.org pull request #5369
Opened 2020-10-01 19:03 UTC by Pomax

Closes https://github.com/mozilla/foundation.mozilla.org/issues/5366

Admin page -> settings -> users -> admin user -> "edit" -> "roles" tab -> observe the checkboxes

Before:

![image](https://user-images.githubusercontent.com/177243/94851807-cbfddd80-03dd-11eb-90bf-7aa93372a7aa.png)

After:

![image](https://user-images.githubusercontent.com/177243/94851955-05cee400-03de-11eb-869f-56279186f381.png)

2020-10-03 03:25 UTC, mmmavis requested changes
<img width="187" alt="image" src="https://user-images.githubusercontent.com/2896608/94982175-584af600-04ed-11eb-9d77-522c7f17a86e.png">

check mark becomes almost invisible

2020-10-05 16:03 UTC, Pomax commented on network-api/networkapi/wagtailcustomization/static/css/admin-interface.css
> +#wagtail .wrapper input[type="checkbox"] {
good call

2020-10-06 00:58 UTC, mmmavis requested changes
the check mark is still pretty invisible to me on Chrome and Firefox 🤔

2020-10-06 15:23 UTC, Pomax commented
turns out the CSS rule for "checked" was less specific than the rule for "focussed"... made them equally specific so the checkmark should be nice and thick green again (once heroku updates)

2020-10-06 16:31 UTC, mmmavis requested changes
Check mark only shows up for me (super light grey) when the checkbox is on hover.

I commented out all `background` and `color` rules in `admin.css` and it seemed to style the check mark properly. Let's give this a try?

2020-10-06 21:19 UTC, mmmavis requested changes

2020-10-06 21:19 UTC, mmmavis commented on network-api/networkapi/wagtailcustomization/static/css/admin.css
> +}
```suggestion
#wagtail .wrapper input[type="checkbox"] {
  vertical-align: middle;
}

#wagtail .wrapper input[type="checkbox"]:before {
  top: calc(50% - 10px);
  left: calc(50% - 10px);
}
```

2020-10-06 21:36 UTC, Pomax commented
That works, but restores the weird background color that my CSS was supposed to solve. However, I don't care enough to revisit this, so let's just merge this in and if that background color bugs anyone, they get to fix it themselves.

![image](https://user-images.githubusercontent.com/177243/95262641-58930c00-07e1-11eb-9935-fc4b78315080.png)

2020-10-06 21:44 UTC, mmmavis approved these changes

2020-10-06 21:45 UTC, merged