(WIP) Criteria dings
mozilla/foundation.mozilla.org pull request #5373
Opened 2020-10-02 23:25 UTC by mmmavis

# :warning WIP

Closes #5308

2020-10-03 00:45 UTC, mmmavis commented on source/sass/buyers-guide/views/product.scss
> -      color: $gray-20;
we no longer have `.separator` elements

2020-10-05 16:32 UTC, Pomax commented
@mmmavis is this still WIP?

2020-10-05 16:34 UTC, Pomax requested changes

2020-10-05 16:34 UTC, Pomax commented on network-api/networkapi/buyersguide/templates/product_page.html
> +          {% include "fragments/product_criterion.html"  with  label=how_does_it_use_data_collected  value=product.how_does_it_use_data_collected  ding_control=product.data_collection_policy_is_bad %
Hm, can we change this name to `show_ding` or even just `ding`? A controller is typically far more elaborate than a boolean.

2020-10-05 16:45 UTC, mmmavis commented
yes this is still WIP

2020-10-05 18:47 UTC, Pomax commented
I guess the question is whether it matters to expose it, since we already have the "warning: privacy not included" text bar. This feels like it's more "decoration", and that warning bar is the real information.

2020-10-06 00:14 UTC, mmmavis commented
@Pomax I checked with Kristina and Sabrina and they both thought the dings are more than just decorative. 

I went with adding `aria-label="This  section requires attention."` to the `<section>` of the relavent criteria because it can signal attention on the "section" overview level.  We could add an `<img> ding` within the `<section>` but assistive technology users will have to get into each section in order to know which specific criteria section requires extra attention, which is probably not ideal.

2020-10-06 00:39 UTC, kristinashu approved these changes
Nice! Design looks good!

2020-10-06 20:42 UTC, Pomax approved these changes

2020-10-06 21:33 UTC, merged