Update PNI page analytics
mozilla/foundation.mozilla.org pull request #5437
Opened 2020-10-13 23:49 UTC by mmmavis

Closes #5239

2020-10-15 17:37 UTC, taisdesouzalessa requested changes
Hey Mavis,

I tested it and found one item that isn't working as expected. **See below**. 

For the action "security expand accordion tap" the name of the product is displaying as "Undefined"

<img width="543" alt="image" src="https://user-images.githubusercontent.com/22157921/96163195-6f66ec00-0ece-11eb-8ee0-f1f06f19192c.png">


Also, I have some comments for 2 things I couldn't test (multiple privacy policy link tap and update article link tap) plus 3 new items I forgot to include in the first iteration (sorry). All of the comments are in our list (column G) for better context: https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit?usp=sharing

2020-10-15 17:43 UTC, mmmavis commented
@taisdesouzalessa thanks for the notes. I'll address those issues soon.

> Also, I have some comments for 2 things I couldn't test (multiple privacy policy link tap and update article link tap)

I can update the example test page. Just a reminder that you can always log in to CMS and add/edit content to suit your testing needs 😉

2020-10-15 17:58 UTC, mmmavis commented on network-api/networkapi/buyersguide/templates/product_page.html
> +          <h3 class="h2-heading mb-4 mb-md-5">{% trans "Updates" %}</h3>
This line was accidentally updated by me in my other PR. It should be using `h2-heading`.

2020-10-15 18:04 UTC, mmmavis commented
PR updated!

2020-10-15 18:27 UTC, taisdesouzalessa commented
> I can update the example test page. Just a reminder that you can always log in to CMS and add/edit content to suit different testing needs 
ahhh true, I keep forgetting that I can edit the CMS. Sorry Mavis! Maybe there is a CMS cheatsheet or something I can do to remember, it is too much to keep in mind...haha.

2020-10-15 19:19 UTC, taisdesouzalessa approved these changes
all good! Thanks, Mavis \0/

2020-10-16 16:45 UTC, Pomax approved these changes

2020-10-16 16:45 UTC, merged