Add created_date field to Products
mozilla/foundation.mozilla.org pull request #5474
Opened 2020-10-19 19:43 UTC by KalobTaulien

Closes #5439 

Simply added a new field. Translations not required on a date field. Field is not required for new products either.

2020-10-19 20:09 UTC, Pomax requested changes
Products already have a review date, the issue was for adding a created_date to Product Updates (found in product_update.py)

2020-10-19 20:12 UTC, Pomax commented
I've updated the issue with acceptance criteria.

2020-10-21 00:24 UTC, KalobTaulien commented
@Pomax I made those updates. Thanks for the feedback! 

One more quick review from your end?

2020-10-21 16:17 UTC, Pomax requested changes
Small thing, but not having nulls is always peace of mind.

2020-10-21 16:17 UTC, Pomax commented on network-api/networkapi/buyersguide/pagemodels/product_update.py
> +        null=True,
we can actually remove this, and structure the migration as you have it right now, but with a third operation for `AlterField` that removes the `null=True`, as every product update will have a value assigned after `set_default_created_date` runs.

2020-10-21 16:22 UTC, Pomax commented on network-api/networkapi/buyersguide/migrations/0007_update_created_date.py
> +    ]
```suggestion
```suggestion
        migrations.AlterField(
            model_name='update',
            name='created_date',
            field=models.DateField(auto_now=True, help_text='The date this product was created'),
        ),
    ]
```

2020-10-21 16:22 UTC, Pomax commented on network-api/networkapi/buyersguide/pagemodels/product_update.py
> +        null=True,
```suggestion
```

2020-10-21 19:19 UTC, Pomax requested changes
https://docs.djangoproject.com/en/2.2/ref/models/fields/#datefield rofflecopters

2020-10-21 19:19 UTC, Pomax commented on network-api/networkapi/buyersguide/migrations/0007_update_created_date.py
> +            field=models.DateField(auto_now=True, null=True, help_text='The date this product was created'),
```suggestion
            field=models.DateField(auto_now_add=True, null=True, help_text='The date this product was created'),
```

2020-10-21 19:19 UTC, Pomax commented on network-api/networkapi/buyersguide/migrations/0007_update_created_date.py
> +            field=models.DateField(auto_now=True, help_text='The date this product was created'),
```suggestion
            field=models.DateField(auto_now_add=True, help_text='The date this product was created'),
```

2020-10-21 19:19 UTC, Pomax commented on network-api/networkapi/buyersguide/pagemodels/product_update.py
> +        auto_now=True,
```suggestion
        auto_now_add=True,
```

2020-10-26 16:59 UTC, KalobTaulien commented
@Pomax I merged in your suggestions, thank you for those! 

Can I get your approval to merge this in?

2020-10-27 21:55 UTC, Pomax approved these changes
nice!

2020-10-28 00:47 UTC, merged