Relocate category nav
mozilla/foundation.mozilla.org pull request #5491
Opened 2020-10-21 21:37 UTC by mmmavis

Closes #5415

2020-10-21 22:32 UTC, mmmavis commented
gonna update this PR and re-request for reviews

2020-10-21 22:37 UTC, mmmavis commented on network-api/networkapi/buyersguide/templates/bg_base.html
> -  <header>
view without whitespace changes should make code review easier

2020-10-21 22:49 UTC, sabrinang requested changes
The selected, current category should be `#000000` to match the border-color underline

2020-10-21 23:17 UTC, mmmavis commented
Updated!

2020-10-22 02:36 UTC, sabrinang approved these changes
Update looks good, thanks!

2020-10-23 17:23 UTC, Pomax approved these changes
lgtm!

2020-10-23 17:42 UTC, mmmavis commented
yay!

2020-10-23 17:42 UTC, merged