Remove MSS badge and add ding to product thumbnails
mozilla/foundation.mozilla.org pull request #5496
Opened 2020-10-22 22:20 UTC by mmmavis

Closes #5425

2020-10-23 02:34 UTC, sabrinang approved these changes
👍

2020-10-23 08:52 UTC, TheoChevalier requested changes

2020-10-23 08:52 UTC, TheoChevalier commented on network-api/networkapi/buyersguide/templates/catalog.html
> +                alt="{% trans " *privacy not included with this product" %}"
Removing this extra space will allow us to translate this once for both attributes

```suggestion
                alt="{% trans "*privacy not included with this product" %}"
```

2020-10-23 17:14 UTC, Pomax approved these changes
r+ with theo's requested fix

2020-10-23 22:42 UTC, Pomax requested changes
[n/a]

2020-10-23 22:42 UTC, Pomax commented on network-api/networkapi/buyersguide/templates/catalog.html
>          <figure class="product-box d-flex flex-column justify-content-between{% if product.draft %} draft-product{% endif %}{% if product.adult_content %} adult-content{% endif %}" data-creepiness="{
```suggestion
        <figure class="product-box d-flex flex-column justify-content-between{% if product.draft %} draft-product{% endif %}{% if product.adult_content %} adult-content{% endif %}{% if product.privacy_ding %} privacy-ding{% endif%}" data-creepiness="{{ product.votes.creepiness.average }}">
```

2020-10-23 22:51 UTC, Pomax approved these changes

2020-10-26 09:02 UTC, TheoChevalier approved these changes
👍 Thanks!

2020-10-27 19:34 UTC, mmmavis commented
I tried rebasing but it took forever to fix conflicts so I've created a new PR for this. See https://github.com/mozilla/foundation.mozilla.org/pull/5535.

Closing this one.

2020-10-27 19:34 UTC, closed without merging