3 page types for PNI products
mozilla/foundation.mozilla.org pull request #5523
Opened 2020-10-26 20:28 UTC by KalobTaulien

Closes #5507
Related PRs/issues #5489

Criteria:
- [x] ProductPage (not abstract, but not creatable through the admin)
- [x] SoftwareProductPage (inherits ProductPage)
- [x] GeneralProductPage (inherits ProductPage)

2020-10-26 20:32 UTC, KalobTaulien commented
@Pomax There are TODO's in this PR because those particular tasks will be taken care of in future tickets (tickets that already exist in this epic)

There's a ProductPage that will hold similar fields for SoftwareProductPage and GeneralProductPages. We inherit form ProductPage so we can collectively get all the products with `ProductPage.objects.all()` and to get into the specific fields we'd use `.specific` on the queryset object. This is better for grouping and filtering similar-but-kind-of-different page types.

2020-10-27 17:36 UTC, Pomax commented on network-api/networkapi/wagtailpages/migrations/0013_productpage_types.py
> +# Generated by Django 2.2.16 on 2020-10-26 20:15
the current pni-v4-2020 only goes up to 0004, so 0013 suggests you'll want to rebase.

2020-10-27 17:39 UTC, Pomax requested changes

2020-10-27 17:39 UTC, Pomax commented on network-api/networkapi/wagtailpages/pagemodels/products.py
> +    ProductPage is the similar page that SoftwareProductPage and
```suggestion
    ProductPage is the superclass that SoftwareProductPage and
```

2020-10-27 17:39 UTC, Pomax commented on network-api/networkapi/wagtailpages/translation.py
> +        'email',
let's keep this list as short as possible until the work is done, so we can add "all the fields" as part of the last "okay these are the things we'll translate" migration.

```suggestion
        'name',
        'company',
        'price',
```

2020-10-27 18:04 UTC, Pomax approved these changes

2020-10-27 18:08 UTC, merged