Position creepy face
mozilla/foundation.mozilla.org pull request #5557
Opened 2020-11-02 21:22 UTC by KalobTaulien

Partially Closes #5412 

**Note** I also made the face disappear when there are no search results. This requires UI testing.

2020-11-02 21:40 UTC, Pomax commented
Scroll through this, it feels like we should probably make the creep-o-meter disappear if it goes past the products, or restrict its position somehow?

E.g. this is a little odd:

![image](https://user-images.githubusercontent.com/177243/97922220-f6aac100-1d10-11eb-8b65-22401c9b9290.png)

2020-11-02 21:58 UTC, sabrinang requested changes
In issue https://github.com/mozilla/foundation.mozilla.org/issues/5412#issue-718353698 under desktop/mobile there is a bullet point: 

- Creepy face appears sticky up until last row of products (just after it so it doesn't block product thumbnail)

I took screenshot and notes of approximately where the face can be sticky up until:
<img width="1646" alt="Screen Shot 2020-11-02 at 1 55 45 PM" src="https://user-images.githubusercontent.com/2492510/97923716-4d18ff00-1d13-11eb-8635-172f88242daa.png">

2020-11-02 22:52 UTC, mmmavis requested changes
Left 2 comments + the hopefully-its-just-me creepy face disappearing issue that I mentioned on Slack.

2020-11-02 22:52 UTC, mmmavis commented on source/js/buyers-guide/search.js
> +    }
Let move this to a function so we can call it in `clearText()` as well.

2020-11-03 22:48 UTC, KalobTaulien commented
Closing this PR as it's been manually merged into #5558

2020-11-03 22:48 UTC, closed without merging