Pni improvements 5571
mozilla/foundation.mozilla.org pull request #5573
Opened 2020-11-04 19:38 UTC by Pomax

Closes https://github.com/mozilla/foundation.mozilla.org/issues/5571

2020-11-04 19:43 UTC, Pomax commented on source/sass/buyers-guide/views/catalog.scss
> +      background-repeat: no-repeat;
100% is cutting off the icon by a single pixel, so this is the simplest solution I can see.

2020-11-04 20:04 UTC, kristinashu requested changes
The icon looks good now! 

The cursor/click area seems good above, below, and on the left side of the icon but is it possible to make it clickable to the right of the icon as well?

2020-11-04 23:23 UTC, Pomax commented
yep, added a bit more spacing to the right side on desktop mode.

2020-11-05 00:28 UTC, kristinashu approved these changes
Nice, thank you!

2020-11-05 17:17 UTC, mmmavis approved these changes
Lovely! Ready for merge!

(I've ticked off the checkboxes in the ticket as well)

2020-11-05 17:17 UTC, merged