New full arrow buttons
mozilla/foundation.mozilla.org pull request #5900
Opened 2020-12-15 23:21 UTC by KalobTaulien

Closes #5790

I rejigged this a bit to clean it up and make it a touch more manageable.

Criteria:
- [x] Make entire section a link

Preview:
![arrows](https://user-images.githubusercontent.com/4743971/102284501-7e2f4680-3ef1-11eb-8a09-fbcaf2464b71.gif)

2020-12-16 00:12 UTC, mmmavis commented
@KalobTaulien @sabrinang 

I haven't done a full code review but I have some colours related questions

1. two custom greys are used as border colour. Any chance we can replace them by brand colours? 
  ```css
  --light-grey: rgb(204, 204, 204);
  --dark-grey: rgb(242, 242, 242);
  ```
2. Hover state of the arrow button has a11y issues. Can we give them a different design treatment?

"Previous/Next" label:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/2896608/102287801-0d3b5f00-3ef0-11eb-9bf2-42fc47bc4127.png">

Link:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/2896608/102287787-03196080-3ef0-11eb-943a-caf112b80c21.png">

2020-12-16 00:13 UTC, mmmavis reviewed
@KalobTaulien @sabrinang 

I haven't done a full code review but I have some colours related questions

1. two custom greys are used as border colour. Any chance we can replace them by brand colours? 
  ```css
  --light-grey: rgb(204, 204, 204);
  --dark-grey: rgb(242, 242, 242);
  ```
2. Hover state of the arrow button has a11y issues. Can we give them a different design treatment?

"Previous/Next" label:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/2896608/102287801-0d3b5f00-3ef0-11eb-9bf2-42fc47bc4127.png">

Link:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/2896608/102288089-96529600-3ef0-11eb-995e-880867e05d83.png">

2020-12-16 00:14 UTC, sabrinang requested changes
- The hover state looks great!
- For 770-1200px viewports, can we reduce space in between so text is more centered?
<img width="894" alt="image" src="https://user-images.githubusercontent.com/2492510/102287822-16c4c700-3ef0-11eb-9cad-127b2f86da72.png">

- For mobile, the text is a bit out of alignment with other content now

<img width="348" alt="image" src="https://user-images.githubusercontent.com/2492510/102287882-352ac280-3ef0-11eb-9faf-5158c3983eac.png">

2020-12-16 00:16 UTC, sabrinang commented
@mmmavis thanks for the feedback and testing out a11y, I will look at the treatment closer

2020-12-21 20:13 UTC, sabrinang requested changes
From Mavis' feedback I looked at colors we can align and a11y, 
- for hover link we can use `$dark-blue` `#0d10bf` instead for better contrast that passess all WCAG contrast check
- for hover background, instead of a new gray we can use the same background colour as the summary box: `#e7e7fc` _(it still fails WCAG AAA but the summary section is also styled like this so I filed a [separate issue](https://github.com/mozilla/foundation.mozilla.org/issues/5950))_

2020-12-22 16:46 UTC, KalobTaulien commented
@sabrinang New colors updated!

2020-12-22 19:24 UTC, sabrinang approved these changes
👍 Great, looks good

2020-12-23 19:36 UTC, mmmavis requested changes
two small requests!

2020-12-23 19:36 UTC, mmmavis commented on source/sass/components/article-page.scss
> +@media (max-width: 1200px) and (min-width: 770px) {
let's replace these numbers with variables

https://github.com/mozilla/foundation.mozilla.org/blob/master/source/sass/variables.scss

2020-12-23 19:36 UTC, mmmavis commented on source/sass/components/article-page.scss
> +  &:hover {
```suggestion
  @include hover-focus-active {
```

2021-01-06 17:11 UTC, mmmavis approved these changes
Yay! Awesome work!

2021-01-06 22:02 UTC, merged