Migrations to create new model, and migrate old data to new data.
mozilla/foundation.mozilla.org pull request #6317
Opened 2021-03-03 20:44 UTC by KalobTaulien

Closes #6012 
Related PRs/issues #6313 (6313 is a follow up ticket)

All we did was:
1. Copy the old model to a new app (so we can remove the old model later) 
2. Copy the data from one model to the other (allowing pk's to change as needed) 
3. Copy the `category` field to `category_new` and fill it with the new model data
4. Remove the old `category` field
5. Rename `category_new` to `category` so the site picks up where it left off, and everything works as expected.
6. De-register the old BuyersGuideProductCategory snippet so editors continue to work with the new model instead of the old model

Testing steps: 
- [ ] Run `inv new-db`. Migrations in wagtailpages numbered 0042 and 0043 should be executed without complaints. 
- [ ] Edit a PNI product in the admin
- [ ] Under the Product Categories are orderables. It should look like nothing has changed but if you click "Edit" on one of the snippets, it should bring you to a URL with `/wagtailpages/` in it. ie. /cms/snippets`/wagtailpages/buyersguideproductcategory/`1/
- [ ] Pull down a copy of the staging database, note the category(ies) on a PNI product. Run the new migrations against localhost. The categories should look the same but the edit URL will change to reflect that the snippet is now in the `wagtailpages` app
- [ ] Check the pni detail view to make sure the template still works as expected.

2021-03-04 01:09 UTC, Pomax commented
Something's not quite right with the migrations, because testing this on staging data shows categories changing:

![image](https://user-images.githubusercontent.com/177243/109894898-1f9d7d00-7c43-11eb-9000-586439d8a7da.png)

I'm pretty sure Google Nest Hub Max was not a valentine's day product =D

2021-03-04 01:10 UTC, Pomax commented
Nav menu definitely also breaks now:

![image](https://user-images.githubusercontent.com/177243/109895031-64291880-7c43-11eb-9219-a55411f4d5a8.png)

2021-03-04 01:11 UTC, Pomax requested changes
this doesn't seem to be working correctly yet.

2021-03-04 01:17 UTC, Pomax commented on network-api/networkapi/wagtailpages/migrations/0044_buyersguideproductcategory_2.py
> +            product_page_category.save()
It feels like this is not doing what it should be thanks to M2M...

2021-03-04 21:04 UTC, KalobTaulien commented
@Pomax This is ready for re-review. I pulled down staging and ran the migrations together and it works now. I ran it 3 times in a row because there were inconsistencies in the results I was getting, but it's working as expected now. 

I'd appreciate if you could also give this a run using the staging database please

2021-03-04 23:03 UTC, Pomax commented
Much better, but it looks like some of the category settings are not getting carried over. Compare the ordering, and entries, 

Foundation site:

![image](https://user-images.githubusercontent.com/177243/110042487-b24d2300-7cfa-11eb-89ac-1f1d4095ff86.png)

This branch:

![image](https://user-images.githubusercontent.com/177243/110042509-ba0cc780-7cfa-11eb-97f0-d81413eef362.png)

2021-03-04 23:04 UTC, Pomax requested changes
so close O_o

2021-03-08 21:30 UTC, KalobTaulien commented
@Pomax This is working for me now. I pulled the staging database, ran the migrations, and got the same categories for both, all in the right order. Could you give this another try?

Localhost:
![image](https://user-images.githubusercontent.com/4743971/110384204-8db6bb00-801a-11eb-97ec-d0239e79bb05.png)

Foundation staging site:
![image](https://user-images.githubusercontent.com/4743971/110384272-a0c98b00-801a-11eb-8e8e-486c361fe53f.png)

2021-03-09 19:48 UTC, Pomax approved these changes
hurray!

2021-03-10 17:44 UTC, merged