Add comments heading
mozilla/foundation.mozilla.org pull request #6337
Opened 2021-03-08 19:20 UTC by Pomax

Related PRs/issues #6200

If `USE_COMMENTO` is enabled, this change adds the "Comments" heading to PNI product pages, as well as Blog pages (but only for blog pages that have commenting enabled in the CMS)

2021-03-08 19:44 UTC, mmmavis approved these changes
Code looks good. I will defer design review to @sabrinang .

@Pomax can you include links to test pages or screencaps for Sabs to 👀 ?

2021-03-08 19:45 UTC, sabrinang commented
Yes please leave links as I'm trying to check out:
https://foundation-s-add-commen-iheucc.herokuapp.com/en/privacynotincluded/
https://foundation-s-add-commen-iheucc.herokuapp.com/en/blog/
but I'm getting this so I don't know if I'm looking at the right spot
<img width="680" alt="image" src="https://user-images.githubusercontent.com/2492510/110372293-f8f49300-8002-11eb-855a-4c4f27e129ff.png">

2021-03-09 16:38 UTC, TheoChevalier requested changes
Can we localize these strings please, even though the comment tool is not (yet) localized?

2021-03-10 17:29 UTC, Pomax commented
@sabrinang  @TheoChevalier I've updated the app settings, so it should work now. Links and screens in the top comment.

2021-03-10 17:36 UTC, TheoChevalier approved these changes
Thanks!

2021-03-10 18:05 UTC, sabrinang reviewed
- can the comment heading/section come after "Related products"?
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/2492510/110675069-5dd8f600-8187-11eb-8b04-3eb2cc5ae031.png">

- for the blog context, the heading should match the style of "Relate content":
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/2492510/110674986-47329f00-8187-11eb-886d-786d5ad66527.png">

2021-03-12 00:34 UTC, Pomax commented
@sabrinang it can, does it need to be full width, then? Because the related products have a different width from the content above them.

2021-03-15 22:02 UTC, Pomax commented on network-api/networkapi/wagtailpages/templates/wagtailpages/blog_page.html
> +      <h2 class="h2-heading">{% trans "Comments" %}</h2>
```suggestion
      <h2 class="h4-heading">{% trans "Comments" %}</h2>
```

2021-03-15 22:48 UTC, Pomax commented
@sabrinang https://foundation-s-add-commen-vndh71.herokuapp.com/en/blog/initial-test-blog-post-with-fixed-title/ is with the blog heading set to h4-heading, just like related:

![screenshot 725](https://user-images.githubusercontent.com/177243/111231057-d126a180-85a5-11eb-9292-5651baf42f5b.png)

2021-03-15 23:16 UTC, sabrinang approved these changes
Thanks for making those headings match Pomax!

2021-03-16 18:30 UTC, merged