updated image size to reduce number renditions
mozilla/foundation.mozilla.org pull request #6384
Opened 2021-03-16 17:54 UTC by danielfmiranda

Closes #6378 

## Checklist

**Changes in Models:**
- [x] [Are my changes backward-compatible]

2021-03-17 22:30 UTC, mmmavis requested changes
We aren't updating packages in this PR so there shouldn't be changes introduced in package-lock.json. Can we remove it from the commit, please?

2021-03-18 22:48 UTC, Pomax requested changes
Note that with https://github.com/mozilla/foundation.mozilla.org/issues/6395 thrown into the mix, we don't just need to update one set's dimensions, we should take out the other three source sets as well.

2021-03-18 22:49 UTC, Pomax commented on network-api/networkapi/buyersguide/templates/buyersguide/catalog.html
>                  media="(max-width: 414px)"
note that as we're reducing the source to a universal "same x1 and x2 at all sizes", we don't need this `media` attribute anymore, and the other `<source>` collections still need to be removed

2021-03-18 22:50 UTC, Pomax commented on network-api/networkapi/buyersguide/templates/buyersguide/catalog.html
> +                  {% image product.image fill-360x360 as img_2x %}
we want 360 for the x1 size, and 720 for the x2 size

2021-03-19 21:21 UTC, danielfmiranda commented
HI Everyone,

I am closing this PR as I have mistakenly added package-lock.json to the list of changes.
 
So instead of keeping this one, which will show a history of adding, deleting, and then re-adding the package-lock.json file, 
I am going to close this PR and create a new one, which will then just show the changes made to the desired file which is "**catalog.html**"

2021-03-19 21:21 UTC, closed without merging

2021-03-19 22:05 UTC, mmmavis commented
Thanks for the update @danielfmiranda .

Don't worry about "polluting" the commit history next time as the commits are squashed when we hit the PR merge button. 😉  https://github.com/mozilla/foundation.mozilla.org/commits/master