Dynamically serve PNI images
mozilla/foundation.mozilla.org pull request #6401
Opened 2021-03-18 16:20 UTC by KalobTaulien

Closes #6400
Related PRs/issues #6378 #6248 #6395 

Replaces `{% image .. %}` with `{% image_url %}` so when an http request is made to the image URL, it will dynamically create an image rendition and serve it. Caching is included, so we don't need to worry about creating multiples of the same renditions over and over again. 

**Note**: I did _not_ adjust the number of thumbnails being generated. That will be taken care of in other upcoming tickets.

2021-03-18 16:26 UTC, Pomax requested changes

2021-03-18 16:26 UTC, Pomax commented on network-api/networkapi/urls.py
> +    ),
Small nit, but let's make this its own `image_url_tag_urls.py` file with some comments that explain that this lets us use an `image_url` tag in our templates, and what it does, in the `wagtailcustomizations` dir, and then include that patthern it exports here? Just to make it much more obvious to future devs (including ourselves) that this is a customization

2021-03-18 17:13 UTC, Pomax commented on network-api/networkapi/image_url_tag_urls.py
> +Typically with Wagtail we use use an {% image img.object fill-XXXxYYY %} template tag
```suggestion
Typically with Wagtail we use an {% image img.object fill-XXXxYYY %} template tag
```

2021-03-18 17:14 UTC, Pomax commented on network-api/networkapi/image_url_tag_urls.py
> +to create an image rendition. These renditions are blocking processes, which is typically
```suggestion
to create an image rendition. Creatingh renditions is a blocking process, which is typically
```

2021-03-18 17:15 UTC, Pomax commented on network-api/networkapi/image_url_tag_urls.py
> +that URL is requests, Wagtail will find the original image, create the rendition, and
```suggestion
that URL is requested, Wagtail will find the original image, create the rendition, and
```

2021-03-18 17:16 UTC, Pomax commented on network-api/networkapi/image_url_tag_urls.py
> +serve the image. This off loads the heavy lifting in the upfront HTTP request and defers
```suggestion
serve the image. This offloads the heavy lifting in the intiial HTTP request and defers
```

2021-03-18 17:16 UTC, Pomax commented on network-api/networkapi/image_url_tag_urls.py
> +the custom URL in this file, along with a slightly different template tag and syntax.
```suggestion
the custom URL declared in this file, along with a slightly different template tag and syntax.
```

2021-03-18 17:17 UTC, Pomax requested changes
mostly phrasing/typos =)

2021-03-18 20:03 UTC, KalobTaulien commented
I'm not sure why exactly, but tests are failing. 

They were originally failing because there were no images attached to a ProductPage in the tests, but then I added that and got another similar error. The test class is  `networkapi.buyersguide.tests.TestBuyersGuidePage`

```
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/wagtail/images/views/serve.py", line 20, in generate_image_url                                                                                                    
    signature = generate_signature(image.id, filter_spec, key)                                                                                                                                                              
AttributeError: 'str' object has no attribute 'id' 
```

This is suggesting the `product.image` doesn't have an actual image attached to it, but I had thought I solved that already. The problem comes up in the about routable pages. The test I was specifically working with was `def about_url_test(..)` and `def test_buyersguide_about_how_to_use_view(..)` (and commented out the rest of them for simplicity)

My current thinking is that `BuyersGuidePage.get_context(...)` isn't providing the right images to the products, or just that some products are missing images. I noticed get_context() is called twice, one with a ProductPage that **has** an image, and a second time where the same ProductPage **doesn't** have an image. 

That is where I'm at right now.

2021-03-18 21:11 UTC, Pomax commented on network-api/networkapi/image_url_tag_urls.py
> +"""
let's put this in `networkapi/wagtailcustomization`?

2021-03-22 14:34 UTC, KalobTaulien commented
Soooooo ran into a funny thing where a bunch of our buyersguide pages fail to load through tests, but load perfectly when user testing. Pomax and I both spent a chunk of time trying to resolve this issue so we can use dynamic iamge URLs but we couldnt find a solution in a timely manner. 

Instead we're going to cut out the renditions we don't need so we can at least flip the switch to fully remove cloudinary and unblock those tickets. Then we'll come back to this a bit later if we determine we still need dynamically generated image URLs.

2021-03-23 18:18 UTC, Pomax approved these changes

2021-03-23 18:34 UTC, merged