WIP: changed article page from using css grid to instead using column count
mozilla/foundation.mozilla.org pull request #6540
Opened 2021-04-12 23:25 UTC by danielfmiranda

Closes #6327

**Link to sample test page**:

## Checklist

**Changes in Models:**
- [ ] [Are my changes backward-compatible]

2021-04-13 00:14 UTC, danielfmiranda commented on network-api/networkapi/wagtailpages/templates/wagtailpages/article_page.html
> +                <a href="#{{ slug }}" class="article-summary-link {% if get_titles|length > 5 %}article-summary-link__two-col{% endif %}">{{ header }}</a>
Checking if the page has more than 5 links, if so, assign "two-col" class.

2021-04-13 00:15 UTC, danielfmiranda commented on source/sass/components/article-page.scss
> +
if there are less than 5 links, the article summary links display block one after the other.

However if there are more than 5 and the two-col class is assigned, they display inline-block to stay aligned with one another in the two column format.

2021-04-13 00:16 UTC, danielfmiranda commented on source/sass/components/article-page.scss
> -        display: grid;
removing old css grid that I added last PR, and using column count instead.

2021-04-13 16:24 UTC, sabrinang approved these changes
It works well! The columns are balanced, the various link amounts arrange nicely and various line lengths work too. Thanks for the update Daniel!

2021-04-14 00:39 UTC, mmmavis requested changes
Lovely! Thanks for setting up test pages and leaving inline comments. 

Let's not use BEM naming convention until the engineering team as a whole agrees to adapt to it for Foundation site codebase. Could you please update `article-summary-link__two-col` to something else? Thanks!

2021-04-14 18:04 UTC, danielfmiranda commented on source/sass/components/article-page.scss
> +.article-summary-link-two-column {
if there are more than 5 items, the article summary links are then given the "Article-summary-link-two-column" class which makes them inline block, to appear with uniform spacing between them

2021-04-14 18:06 UTC, danielfmiranda commented on source/sass/components/article-page.scss
> +.article-links-two-column {
if there are more than 5 items, the article links  div is then given the "Article-links-two-column" class which gives it a column count of two, only above the medium breakpoint. 

If it is tablet-sized or under, the links display block one above another.

2021-04-14 18:07 UTC, danielfmiranda commented
Hi @mmmavis Thank you for the catch and for taking a look! I have updated the CSS names like requested :)

2021-04-15 06:09 UTC, mmmavis approved these changes
Woohoooo summary link section is looking sharp ✨

2021-04-15 06:45 UTC, merged