Fix the language picker
mozilla/foundation.mozilla.org pull request #6765
Opened 2021-05-27 23:03 UTC by Pomax

Closes #6710

Waiting for the review app to finish building before giving STR.

2021-05-27 23:33 UTC, Pomax commented
A potential bug: 
- I added Dutch as locale
- I clicked "translate this page" for the homepage
- this page has an EN field `hero_headline` with content `Plant bad attention painting clearly. Hold off allow maybe significant stop.`, which is too long, but the `load_fake_data` process doesn't care.
- I exported the strings as .po file and added a dutch translation:
```
msgctxt "hero_headline"
msgid "Plant bad attention painting clearly. Hold off allow maybe significant stop."
msgstr "Plant slecht attentieschilderij duidelijk. Wacht sta toe misschien stop."
```
- uploading this .po file and publishing the page leads to an error, claiming the field content is too long. 
- I made the string drastically shorter, but it still complains:

![{5C23F111-2458-4457-A107-68C7D05C77A4}](https://user-images.githubusercontent.com/177243/119909171-1aca2b80-bf09-11eb-9c4f-3ead2adfa2d3.png)

- I figured I'd blank the string again, so that it doesn't _have_ a translation:

```
msgctxt "hero_headline"
msgid "Plant bad attention painting clearly. Hold off allow maybe significant stop."
msgstr ""
```
- uploading this .po file and publishing _does not remove the translation_

So it feels like there might be several bugs here.

2021-05-28 07:31 UTC, TheoChevalier commented
> uploading this .po file and publishing does not remove the translation and preserves the last translation.

I suspect uploaded .po files are treated differently and are _merged_ only, while actually deleting a translation from Pontoon will work as intended.
Here you should be able to just click the Edit button, remove the translation and hit save + publish


> I went to the original page and updated the field to have a shorter string, and published that.

You need to sync the page after publishing to propagate the change (this allows for copy review before content gets sent for translation)

2021-05-28 10:14 UTC, TheoChevalier approved these changes
Did further testing (and added other locales for the homepage, too), and I can confirm this fixes #4290 🎉

2021-05-31 16:38 UTC, KalobTaulien requested changes
Code looks good 👍  Can confirm the intended code does the job. 

Just need to figure out the CSRF thing with CloudFlare. Wonder if we can wrap the `set_language` view in a `csrf_exemp` decorator? 

**Edit**: I made another comment (below) about removing or using different DRF settings for manual page translations.

2021-05-31 16:38 UTC, KalobTaulien commented on network-api/networkapi/templates/fragments/language_switcher.html
> +  {% csrf_token %}
We'll want to figure out how to do this without CSRF to continue using CloudFront in production without running into caching issues.

2021-05-31 16:54 UTC, KalobTaulien commented
Things I found during testing. 

When manually translating through the UI we need to remove this from our settings (or change it to allow writing)
![image](https://user-images.githubusercontent.com/4743971/120223194-72fd7800-c1fe-11eb-9183-b1b265012f9f.png)

```python
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ]
}
```
☝️ With that setting on (which it currently is) the terminal says:
> AssertionError: Cannot apply DjangoModelPermissionsOrAnonReadOnly on a view that does not set `.queryset` or have a `.get_queryset()` method.

This is something I missed in the initial setup. But we can add it at any point in time (and since this might be our last small PR for wagtail-localize it might be good to add it here).

2021-05-31 19:00 UTC, Pomax commented on network-api/networkapi/templates/fragments/language_switcher.html
> +  <input name="next" type="hidden" value="{% get_unlocalized_url page current_language %}" />
```suggestion
  <input name="next" type="hidden" value="{% get_unlocalized_url page current_language %}" />
```

2021-05-31 19:00 UTC, Pomax commented on network-api/networkapi/templates/fragments/language_switcher.html
> +  <input name="next" type="hidden" value="{% get_unlocalized_url page current_language %}" />
urls.py already has csrf exemption:
```
    # set up set language redirect view
    path('i18n/setlang/', csrf_exempt(set_language), name='set_language'),
```

2021-05-31 19:04 UTC, KalobTaulien approved these changes

2021-05-31 19:21 UTC, merged