Snippet translations + translatable fields
mozilla/foundation.mozilla.org pull request #6777
Opened 2021-05-31 19:39 UTC by KalobTaulien

Closes #6708
Related PRs/issues #6703 

## Acceptance criteria 

> Note: Don't forget to reference [the document from Step 5 #6707](https://docs.google.com/spreadsheets/d/1AU7pxboZoBiVcbTpZO-VUMAhxZwx5mdEH_FBLfo2D-w/edit#gid=0)

- [x] Create migrations for all snippets. [This document](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html#making-snippets-with-existing-data-translatable) will be _very_ helpful. We need to bootstrap migrations for each model. 
  - [x] Make sure all snippet models are translated. 
  - [x] Make sure all snippet fields have `translatable_fields = [ .. ]` set on them 
  - [ ] Make sure tests still pass. May need to do some adjusting for new language headers in the `request` object, particularly around redirects. 
- [ ] Get Theo to review this (specifically, Theo) to make sure all the fields are the right translation type.

2021-05-31 19:47 UTC, KalobTaulien commented
Locally all the tests pass.

@Pomax I pinged you for code review on this. 
@TheoChevalier I pinged you for semi-code review but mostly to make sure I got all the fields right. Your doc was very helpful. I made some notes in the doc too and highlighted some lines for you to take a look at.

2021-05-31 23:36 UTC, Pomax requested changes
some minor notes, and a question

2021-05-31 23:36 UTC, Pomax commented on network-api/networkapi/news/models.py
> +    class Meta(TranslatableMixin.Meta):
Let's check if this is actually necessary or not. If we don't need to mark the Meta class as translatable, that saves some migration work. (not much, but "not doing anything we don't need to do is worth not doing" =D)

2021-05-31 23:36 UTC, Pomax commented on network-api/networkapi/wagtailpages/pagemodels/base.py
> +from wagtail_localize.fields import SynchronizedField
```suggestion
from wagtail_localize.fields import SynchronizedField, TranslatableField
```

2021-05-31 23:36 UTC, Pomax commented on network-api/networkapi/wagtailpages/pagemodels/campaigns.py
> +from wagtail_localize.fields import SynchronizedField
```suggestion
from wagtail_localize.fields import SynchronizedField, TranslatableField
```

2021-05-31 23:36 UTC, Pomax commented on network-api/networkapi/wagtailpages/pagemodels/dear_internet.py
> +from wagtail_localize.fields import SynchronizedField
```suggestion
from wagtail_localize.fields import SynchronizedField, TranslatableField
```

2021-05-31 23:36 UTC, Pomax commented on network-api/networkapi/wagtailpages/pagemodels/index.py
> +from wagtail_localize.fields import SynchronizedField
```suggestion
from wagtail_localize.fields import SynchronizedField, TranslatableField
```

2021-05-31 23:36 UTC, Pomax commented on network-api/networkapi/wagtailpages/pagemodels/primary.py
> +from wagtail_localize.fields import SynchronizedField
```suggestion
from wagtail_localize.fields import SynchronizedField, TranslatableField
```

2021-05-31 23:36 UTC, Pomax commented on network-api/networkapi/wagtailpages/pagemodels/products.py
> +from wagtail_localize.fields import SynchronizedField
```suggestion
from wagtail_localize.fields import SynchronizedField, TranslatableField
```

2021-05-31 23:36 UTC, Pomax commented on network-api/networkapi/wagtailpages/pagemodels/publications/article.py
> +from wagtail_localize.fields import SynchronizedField
```suggestion
from wagtail_localize.fields import SynchronizedField, TranslatableField
```

2021-05-31 23:36 UTC, Pomax commented on network-api/networkapi/wagtailpages/pagemodels/publications/publication.py
> +from wagtail_localize.fields import SynchronizedField
```suggestion
from wagtail_localize.fields import SynchronizedField, TranslatableField
```

2021-06-01 14:30 UTC, TheoChevalier commented
I’ve made a few changes to the spreadsheet (all highlighted in orange), mostly answering your questions.
A few fields in snippets are not properly hooked (I’ve highlighted them in red in the Snippets sheet)

Also hit a few errors/have some questions:


### PNI General product:
Translating a general product raises:
<img width="848" alt="Capture d’écran 2021-06-01 à 15 48 46" src="https://user-images.githubusercontent.com/1294206/120334546-9ef52800-c2e8-11eb-8923-9f64b16b41ed.png">

### Campaign page
Translating a campaign page that has a petition + donate snippets raises:
<img width="516" alt="Capture d’écran 2021-06-01 à 14 15 12" src="https://user-images.githubusercontent.com/1294206/120334764-d2d04d80-c2e8-11eb-8865-9c101230cc3d.png">


### Youtube Regrets
`Regret stories` are missing. Is this because it’s a block and not part of the model?

### Article pages:
For Text and ID https://docs.google.com/spreadsheets/d/1AU7pxboZoBiVcbTpZO-VUMAhxZwx5mdEH_FBLfo2D-w/edit#gid=0&range=A43 these are fields I’ve found at the bottom of article pages, but I haven’t been able to find them in the model code
<img width="1116" alt="Capture d’écran 2021-06-01 à 16 04 55" src="https://user-images.githubusercontent.com/1294206/120337379-2a6fb880-c2eb-11eb-8744-d0effc43e9ee.png">

### Homepage
Here too, a lot of the content is not localized, is this because these are blocks and it will come later?
Also it seems every page picker field need to be `Translatable`, otherwise links will point to /en/…
This affects all page pickers in News you can use, Spotlight, Take action, etc

2021-06-01 19:02 UTC, KalobTaulien commented
Hey @TheoChevalier Thank you for digging into this! 

1. Ahh there was a typo in the PNI products. Glad localize found that. Should be fixed now. 
2. Not sure how but I missed the MozfestHomepage, so Ive added that in. 
3. I made some changes you suggested from your doc as well. 
4. The Homepage [has translatable_fields here](https://github.com/mozilla/foundation.mozilla.org/pull/6777/files#diff-acb6632b9522d55f99ba1616f58beda704393419a37a5674e86d2f7e12d825f6R771-R791) its just not easy to see in the Changed Files tab. Let me know if I'm missing any. 
5. Campaign pages should translate now. But let me know if it doesn't and how you got to that point. They worked locally for me.

2021-06-01 19:19 UTC, KalobTaulien commented
We've run into an issue with Wagtail Footnotes. The Footnote model and the localize Translate model both have `uuid = ...` in them causing a conflict. I pinged Karl about this since I'm unsure how to proceed with this properly.

2021-06-02 18:05 UTC, TheoChevalier commented
> Hey @TheoChevalier Thank you for digging into this!
> 
>     1. Ahh there was a typo in the PNI products. Glad localize found that. Should be fixed now.

Yup, thanks!
> 
>     2. Not sure how but I missed the MozfestHomepage, so Ive added that in.

Hm, I’m getting this error when translating it
<img width="499" alt="Capture d’écran 2021-06-02 à 20 02 38" src="https://user-images.githubusercontent.com/1294206/120530206-2a4be780-c3d5-11eb-99fc-bb5b00e15509.png">


>     3. I made some changes you suggested from your doc as well.
> 
>     4. The Homepage [has translatable_fields here](https://github.com/mozilla/foundation.mozilla.org/pull/6777/files#diff-acb6632b9522d55f99ba1616f58beda704393419a37a5674e86d2f7e12d825f6R771-R791) its just not easy to see in the Changed Files tab. Let me know if I'm missing any.


> 
>     5. Campaign pages should translate now. But let me know if it doesn't and how you got to that point. They worked locally for me.

Thanks! I’m able to submit now, but I end up with an empty French page… Do you see that as well?
I just clicked "Translate this page" on the first campaign page I saw into the two locales I’ve set up (German & French), then edited the French translation
<img width="796" alt="Capture d’écran 2021-06-02 à 19 38 30" src="https://user-images.githubusercontent.com/1294206/120527308-18b51080-c3d2-11eb-9f58-b1bc2488bbcf.png">


Another thing I noticed, strings from the Promote tab are missing from all pages (SEO title and description), I suspect these are a bit special?

2021-06-02 19:20 UTC, KalobTaulien commented
Hey @TheoChevalier I'll take a look at the campaign pages acting up in a bit. Thanks for catching that! 

I opened an issue here #6790 regarding the footnotes issue. I've disabled footnote translations for the time being in this PR so we can land this asap.

2021-06-02 23:05 UTC, Pomax requested changes
so it looks like snippets are not actually working, let's get some time with Karl to figure this one out.

2021-06-03 15:28 UTC, KalobTaulien commented on network-api/networkapi/wagtailpages/migrations/0012_bootstrap_migrations.py
> +        BootstrapTranslatableModel('wagtailpages.FocusArea'),
Manual migration. Copy and paste got me here. Will remove, thanks for finding this!

2021-06-03 15:29 UTC, KalobTaulien commented on network-api/networkapi/mozfest/models.py
> +        # TranslatableField('footnotes'),
We do! And good call. Will do that now.

2021-06-03 15:31 UTC, KalobTaulien commented on network-api/networkapi/wagtailpages/pagemodels/products.py
> +    ]
This is a good question for Karl tomorrow. I also don't like looking at this. It feels very.. tedious.

2021-06-04 21:48 UTC, Pomax requested changes
looks like snippets at least work now, but we'll need to comb the code on Monday to make sure we caught all of them.

2021-06-09 21:03 UTC, Pomax approved these changes
Let's get this landed and then deal with the followup as new work.

2021-06-10 15:56 UTC, KalobTaulien commented
Ticket made for the campaign page problem. #6851

2021-06-10 15:57 UTC, merged