Wagtail 2.12.5
mozilla/foundation.mozilla.org pull request #6922
Opened 2021-06-22 18:41 UTC by KalobTaulien

Closes #6852 

Teeny tiny version bump due to a [Wagtail security patch](https://docs.wagtail.io/en/stable/releases/2.12.5.html#cve-2021-32681-improper-escaping-of-html-cross-site-scripting-in-wagtail-streamfield-blocks)

2021-06-22 23:03 UTC, Pomax commented
Hm, looking at https://foundation-mozilla-org-visual-ci.s3.us-east-1.amazonaws.com/pull/6922/merge/main/chromium-500/localhost-8000/en/what-you-can-do/screenshot.png and https://foundation-mozilla-org-visual-ci.s3.us-east-1.amazonaws.com/pull/6922/merge/main/chromium-1200/localhost-8000/en/what-you-can-do/screenshot.png, did this break the metadata package?

2021-06-22 23:03 UTC, Pomax requested changes
might have issues with metadata?

2021-06-23 20:30 UTC, KalobTaulien commented
Looks like issues with metadata. Will look into this this afternoon. I didn't get this issue locally when clicking around, so I might need to nuke docker and re-test this. 

And this is why we have automated testing :D

2021-06-23 21:25 UTC, KalobTaulien commented
I checked this out. Doesnt seem to happen for me with staging data. Im unsure why the vis. diff. would see those errors, and percy wouldn't. Just to make sure, I nuked docker and rebuilt from scratch, testing the erroring URLs, then loaded in staging data, and tested the same URLs and got no issues. 

If you get time, I wouldn't mind if you double checked this locally too @Pomax even just as a sanity check for me

2021-06-23 23:10 UTC, Pomax approved these changes
This works fine as far as I can tell!

2021-06-23 23:10 UTC, merged