Integration - YouTube regrets 2021
mozilla/foundation.mozilla.org pull request #6968
Opened 2021-07-02 13:47 UTC by chris-lawton

Closes #6949, #6953, #6954, #6955, #6956, #6963, #6964, #6967

Integration branch for the YouTube regrets 2021 landing page

2021-07-05 15:36 UTC, KalobTaulien approved these changes
One major thing I noticed was the drawers don't work at all on localhost. Not sure if that's intentional at the moment or not, but I see we have a bunch of JavaScript implemented to make it work. And there are sections of content that haven't been properly filled in from the design yet (but that could be because we didn't have the content at the time this PR was submitted, I'll admit I'm a bit behind on that one). 

I'm going to approve this because we need to get this onto a review app for testing ASAP, even though it still needs more work. This may result in a bunch of follow-up tickets.

2021-07-05 15:36 UTC, KalobTaulien commented on network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2021/fragments/hero.html
> +          <p class="body-large">Mozilla and 37,00 YouTube users conducted a study to better understand harmful YouTube recommendations. <span class="fst-italic">This is what we learned</span>.</p>
Needs translation template tag

2021-07-05 15:36 UTC, KalobTaulien commented on network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2021/fragments/intro.html
> +      <p class="fw-bold">We now know that YouTube is recommending videos that violate their very own policies and harm users around the world — and that needs to stop.</p>
Also needs `{% translate ".." %}` here

2021-07-05 15:36 UTC, KalobTaulien commented on network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2021/fragments/our-research.html
> +        {% blocktrans %}
With `{% blocktrans %}` let's trim it with `{% blocktrans trimmed %}`

2021-07-05 15:36 UTC, KalobTaulien commented on source/images/youtube-regrets/close.svg
> +<svg width="69" height="69" fill="none" xmlns="http://www.w3.org/2000/svg"><path stroke="#000" d="M43.9531 43.6524L26.2025 25.9018M43.6563 25.9034L25.9057 43.6539"/><circle cx="34.9314" cy="34.9258"
SVG's might be compressable using `svgo`.

2021-07-05 15:42 UTC, KalobTaulien requested changes
These changes need to happen before we can merge this in otherwise it doesn't pass our CI. You should be able to just click "Commit suggestion" in the GitHub UI as a fast way of applying the fixes.

2021-07-05 15:42 UTC, KalobTaulien commented on network-api/networkapi/views.py
> +   return render(request, 'wagtailpages/pages/youtube-regrets-2021/youtube_regrets_2021.html')
```suggestion
    return render(request, 'wagtailpages/pages/youtube-regrets-2021/youtube_regrets_2021.html')
```

Flake8 needs a multiple of 4.

2021-07-05 15:42 UTC, KalobTaulien commented on network-api/networkapi/views.py
> +
```suggestion


```
Flake8 needs 2 blank lines.

2021-07-05 15:44 UTC, KalobTaulien approved these changes

2021-07-06 15:36 UTC, KalobTaulien reviewed
One-off hex colors that don't need a variable [yet]. Disable style linting for these.

2021-07-06 15:36 UTC, KalobTaulien commented on source/sass/views/youtube-regrets-2021.scss
> +        }
```suggestion
        &::before {
          /* stylelint-disable */
          background-color: #FBD5D7;
          /* stylelint-enable */
        }
```

2021-07-06 15:36 UTC, KalobTaulien commented on source/sass/views/youtube-regrets-2021.scss
> +        }
```suggestion
        &::before {
          /* stylelint-disable */
          background-color: #FC4147;
          /* stylelint-enable */
        }
```

2021-07-06 15:36 UTC, KalobTaulien commented on source/sass/views/youtube-regrets-2021-carousel.scss
> +    }
```suggestion
    span {
      /* stylelint-disable */
      color: #d63126;
      /* stylelint-enable */
    }
```

2021-07-06 16:51 UTC, KalobTaulien commented on source/images/youtube-regrets/close.svg
> +<svg width="69" height="69" fill="none" xmlns="http://www.w3.org/2000/svg"><path stroke="#000" d="M43.9531 43.6524L26.2025 25.9018M43.6563 25.9034L25.9057 43.6539"/><circle cx="34.9314" cy="34.9258"
Ticket here #6983

2021-07-06 17:26 UTC, merged

2021-07-06 17:33 UTC, danielfmiranda reviewed
Hi All! Thank you for tagging me in this PR, I have given it a look on my local machine and can confirm that the youtube-regrets-2021 path takes me to the landing page, and that the content on the landing page works as designed.

Awesome work, I am approving!