update all homepage fragments to pull from localized content
mozilla/foundation.mozilla.org pull request #7067
Opened 2021-07-12 17:37 UTC by Pomax

Closes https://github.com/mozilla/foundation.mozilla.org/issues/7034
Related PRs/issues https://github.com/mozilla/foundation.mozilla.org/issues/7066

This updates the template fragments used by the homepage, making sure to use the `.localized` property for any page that is a foreignkey/M2M/etc to another page in the CMS.

2021-07-12 17:59 UTC, KalobTaulien requested changes

2021-07-12 17:59 UTC, KalobTaulien commented on network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/news_you_can_use.html
> +      {% with localized=item.blog.localizes %}
```suggestion
      {% with localized=item.blog.localized %}
```

2021-07-12 17:59 UTC, KalobTaulien commented on network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/spotlight_posts.html
>      {% endfor %}
```suggestion
    {% endwith %}
    {% endfor %}
```

2021-07-13 16:43 UTC, KalobTaulien approved these changes

2021-07-13 17:25 UTC, TheoChevalier approved these changes

2021-07-13 17:27 UTC, merged