Add script to generate DNS records for different Sites in review apps
mozilla/foundation.mozilla.org pull request #7073
Opened 2021-07-13 14:16 UTC by tomusher

As part of #5736, this adds a script which adds DNS records for the foundation and mozfest site to AWS on the creation of review apps, then tears them down when the review app is removed.

2021-07-13 17:31 UTC, Pomax reviewed
let's land this and see how it holds up!

2021-07-13 17:32 UTC, Pomax approved these changes

2021-07-13 17:33 UTC, Pomax requested changes
I spoke too soon: flake8 is unhappy with the formatting, so we'll need to fix that before we can land this.

2021-07-19 15:13 UTC, benhohner commented
@tomusher @Pomax what do we need to do to finish this up?

2021-08-11 16:29 UTC, merged