WIP: Hero video and images
mozilla/foundation.mozilla.org pull request #7079
Opened 2021-07-14 17:25 UTC by danielfmiranda

Closes #
Related PRs/issues #

**Link to sample test page**:

## Checklist

_Remove unnecessary checks_

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

2021-07-15 18:37 UTC, sabrinang requested changes
Responsive images and video work on the pages as well as the stop/play video feature.

I think the height shouldn't be taller than the home's hero and if they match these hero banner assets could be reusable between them and it gives one less different dimension to consider.
<img width="1683" alt="Screen Shot 2021-07-15 at 11 23 06 AM" src="https://user-images.githubusercontent.com/2492510/125838441-e8150e41-561a-4ee2-913a-06aabbd19e2f.png">

In the CMS, should there be some validation feedback here if both are entered or it could be formatted in a way that it is clear you can do either video or image but not both. Currently, if the editor fills in both fields the video shows. 
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/2492510/125839051-16c52cd8-5adf-4182-8d08-3d25cd4a0b3c.png">

2021-07-16 01:04 UTC, danielfmiranda commented
Hi @sabrinang! I have updated the size of the hero video/image to match the size of the banner on the homepage, as well as updated the layout of the CMS fields and added some validation. They are now both under a "hero video/image" section, and it will not let users save the page with a video and image set, just one or the other. 

These changes are now live and ready for re-review, thanks!

2021-07-19 16:20 UTC, sabrinang approved these changes
Thanks for making the updates to the height and layout in the CMS Daniel, looks good.

2021-07-21 17:34 UTC, KalobTaulien approved these changes
Approving. One small commit suggestion (but please 2x check it first)

2021-07-21 17:34 UTC, KalobTaulien commented on network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/blog_page_heroguts.html
> +{% load wagtailcore_tags wagtailimages_tags i18n static%}
```suggestion
{% load wagtailimages_tags %}
```

2021-07-21 18:53 UTC, danielfmiranda commented
@KalobTaulien thanks for the suggestion! I have tested it out on my local machine and can confirm that it brings no undesired side effects, so I have made those changes and commited them to the repo.

 I also found that this repo was experiencing the pause button shifting issue that you mentioned in #7103, so I have added the fix to this PR as well.

2021-07-21 18:54 UTC, merged