WIP: background looping video streamfield
mozilla/foundation.mozilla.org pull request #7103
Opened 2021-07-20 04:20 UTC by danielfmiranda

Closes #6981 

**Link to sample test page**:

## Checklist

_Remove unnecessary checks_

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

2021-07-20 18:02 UTC, sabrinang requested changes
The component on the page is responsive, pause/plays accordingly and is a good height for a background looping video.

For the format in the CMS:
- can staff use existing Vimeo videos or do they have to use uploaded ones from our account?
- since the other video component allows videos from YouTube, would that be a possibilities here? (so sources can be aligned or similar)
- the help text “Visit your desired video on Vimeo, then click "Advanced", "Distribution", and "Video File Links". Copy and paste the link here.” it is a bit unclear. I couldn't see it from a public video and my 1pass isn't working to check from an account, do users have to log into the account?

2021-07-20 18:28 UTC, danielfmiranda commented
Hi @sabrinang! 

- Staff would have to use videos that are uploaded to the teams vimeo account in order to access the link.
- I dont believe that can be a possibility here, as youtube provides no way to access a video through a 3rd party video player, with the exception of an iframe which is what we are using in the original video block. 
- Users do need to log in to the 1password vimeo account, as only vimeo pro users can access the mp4 link required to work with this block. I have updated the text to make it a little more detailed!

2021-07-20 19:07 UTC, sabrinang approved these changes
Great! Thanks Daniel for clarifying that and accompanying the help text 👍

2021-07-21 17:22 UTC, KalobTaulien requested changes
Code looks good as far as I can tell. But when user testing the "Play" button (when paused) moves to the bottom left of the video, and get's cut off a bit. Example below:

![image](https://user-images.githubusercontent.com/4743971/126532065-8a7f2114-d495-4be3-be1f-58976dc633bc.png)

2021-07-21 19:07 UTC, danielfmiranda commented
Hi @KalobTaulien  thanks for the catch! Oddly enough it looks that issue does not appear on firefox but did appear in chrome.

I was able to find a fix which is now included in the PR and live on the review app, and have now re-requested review! Thanks in advance

2021-07-22 19:11 UTC, KalobTaulien approved these changes

2021-07-22 22:07 UTC, merged