7028 Intregrating Tailwind and applying it to the style-guide
mozilla/foundation.mozilla.org pull request #7140
Opened 2021-07-26 23:05 UTC by fessehaye

Closes #7037 

Integrating tailwindCSS into the foundation site!
* Added tailwindCSS to our POSTCSS build and a few watch scripts on monitors html and JSX classes changes
* Replaced `network-api/networkapi/templates/partials/footer.html` with new tailwind Classes
* Replaced `/style-guide` as well

Notes on how to play around with the Tailwind classes:
* https://tailwindcss.com/docs/editor-support Strongly recommend you install the tailwind intellsense plugin
<img width="1227" alt="Screen Shot 2021-07-26 at 4 57 07 PM" src="https://user-images.githubusercontent.com/2374073/127069657-53941ee3-da3c-4b48-8fd3-875fb30f5650.png">

* If the plugin is not working try locally installing tailwind outside of docker by `npm install` from the root directory!
* All tailwind classes are prefixed with `tw-` to prevent conflicts with existing CSS and bootstrap.
* We are using the JIT interpreter so you can generate your own classes as well `ex:tw-text-[#34543f]` https://tailwindcss.com/docs/just-in-time-mode
* the buttons and dropdown are stilling using BT classes until we go and replace all of the buttons/form elements
* All tailwind configs are made in the `tailwind.config.js`

2021-07-29 23:12 UTC, sabrinang requested changes
Thanks for updating the style guide Simon! I noticed a few things that could be updated:
- the boxes that contain the color swatch seems to have shifted inside or became thicker (it can match what we had previously)
- the $red color displays the blue color (change back to red)
- there a space missing after the title and parentheses for some gradient swatches
- change Design alias names for "phone" and "phone" to be "mobile (portrait)" and "mobile (landscape)"
- I noticed colors displayed as rgba values in the inspector, will we not have hex # values anymore?
- mobile view: color swatches look cleaner before taking up the whole width as it looks varied in the update (match what we had previously)
- mobile view: the breakpoint table is cut off on mobile (make it horizontally scrollable?)  

<img width="835" alt="image" src="https://user-images.githubusercontent.com/2492510/127576872-d70d1980-5c5c-4e25-888d-6a54bdf1b6ca.png">

2021-08-03 19:01 UTC, KalobTaulien approved these changes
Code looks good to me. I like the `.tw-` prefix, that makes bootstrap conflicts less of a problem, so thank you for adding that in! 

I left a couple of code cleanup comments. But overall this is looking good. I'm going to give this an R+ as long as we address the code cleanup (in future tickets or now, I just don't want it to be forgotten). I still think we should have at least 2 devs review this though since this is a big thing moving forward.

User testing looks good for the footer. It looks like Sabrina has great feedback about the styleguide page which should be addressed before merging this in.

2021-08-03 19:35 UTC, fessehaye commented on source/sass/type.scss
> +  @apply tw-font-normal tw-mb-4 tw-text-black tw-tracking-normal tw-font-zilla tw-text-[22px] tw-leading-[1.3] medium:tw-text-[24px];
Probably will refactor the headings another way in the future, either as components or part of a tailwind component plugin!

2021-08-04 16:19 UTC, danielfmiranda approved these changes
Hi Simon, thanks for tagging me in this! I think the code looks good, and like Kalob had mentioned earlier, I am a fan of the tw- prefix, as it makes it easier to see whether or not a component is using bootstrap classes still or tailwind. I am thinking this will be helpful when migrating in the future!

2021-08-04 19:40 UTC, KalobTaulien approved these changes

2021-08-04 20:24 UTC, merged