6987 Customize Tailwind Spacing Units
mozilla/foundation.mozilla.org pull request #7175
Opened 2021-08-05 05:44 UTC by fessehaye

Please review #7040 first!

Redoing spacing units based on Figma design system, should be reviewed before people try to use tailwind for other tickets not related to the Tailwind Epic!

2021-08-05 16:29 UTC, KalobTaulien requested changes
As far as I can tell the code looks good. But percy has flagged some margin/padding changes. Let's get a designer to review this as well.

2021-08-09 20:23 UTC, sabrinang submitted a review, later dismissed
For the figma design file, I've added the sizing/spacers on the [grid & layout page](https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/?node-id=312%3A354) and in the plug-in: 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/2492510/128768446-14e3095c-952a-4e03-b573-d5818aa6d188.png">

@fessehaye I was able to add 0, px, 2.5 as figma components however I can't add "2.5" as a design token in [the plugin](https://docs.tokens.studio/tokens/creating-tokens) as the . separates the name and doesn't store the token in the plugin. Any tips on how you are naming fraction values and I don't know if you had the same issue in the code?

2021-08-11 18:15 UTC, KalobTaulien requested changes
This is looking good. Let's use a standardized "debug" term for our context processors so that it matches the backend. Everything else looks good. Ping me for a re-review when it's ready!

2021-08-11 18:15 UTC, KalobTaulien commented on network-api/networkapi/context_processor.py
> +    return{"debug_flag":debug_flag}
```suggestion
    return {"debug": settings.DEBUG}
```

2021-08-11 18:15 UTC, KalobTaulien commented on network-api/networkapi/templates/pages/base.html
> +      {% if debug_flag %}<link rel="stylesheet" href="{% static "_css/tailwind.compiled.css" %}">{% endif %}
```suggestion
      {% if debug %}<link rel="stylesheet" href="{% static "_css/tailwind.compiled.css" %}">{% endif %}
```

2021-08-11 22:37 UTC, sabrinang approved these changes
Great thanks for updating them to whole numbers for the naming Simon!

2021-08-12 00:17 UTC, merged