fix the relocalized-url tag, and update some more templates to use it
mozilla/foundation.mozilla.org pull request #7236
Opened 2021-08-18 18:45 UTC by Pomax

Closes https://github.com/mozilla/foundation.mozilla.org/issues/6965 while also fixing up the `relocalized_url` template tag necessary for resolving that issue.

The STR will require grabbing a copy of the most recent production data, so that you have real localized content to test on.

- when on `/de/` the `/blog` index page should link to `/de/` links for all cards rather than `/en/`
- same for the `/campaigns` index page.
- the PNI homepage should have categories and products that all link to the correct locale (`en` on EN, `de` on DE, etc)
- the PNI "all" category and logo should point to the homepage on the current locale
- "related products" for PNI products should have URLs for the current locale

Also note that the blog card has had the code for "showing tags" removed, since we haven't exposed that in years and we're already working on taging tags out (for UI purposes).

2021-08-19 16:02 UTC, TheoChevalier requested changes
Working well overall, just spotted a couple areas we will need to fix, that don’t seem hard to fix (?)
Also tested the Blog set component, blog titles have the localized URL, but categories don’t. 

<img width="830" alt="Capture d’écran 2021-08-19 à 17 08 22" src="https://user-images.githubusercontent.com/1294206/130100826-f3bb4fc0-b01e-420d-a508-cc521575a49f.png">

<img width="1177" alt="Capture d’écran 2021-08-19 à 17 53 25" src="https://user-images.githubusercontent.com/1294206/130102269-44cc0685-599f-4139-a361-6890f7746a30.png">


<img width="839" alt="Capture d’écran 2021-08-19 à 17 57 27" src="https://user-images.githubusercontent.com/1294206/130102405-ce67d4cc-cb30-4cb0-8080-fffe170fabaf.png">

2021-08-19 17:13 UTC, TheoChevalier approved these changes
Actually, the category URL was fixed in the other PR, and I just noticed the faker title issue happens on another PR, so it’s definitely not caused by this code

2021-08-31 23:42 UTC, Pomax commented
I don't know why, but this PR causes a redirect test that passes in `master` to fail. I'll have to dig into why.

2021-09-01 23:24 UTC, Pomax commented
So https://github.com/mozilla/foundation.mozilla.org/pull/7236/files#diff-2a95e5e43636ba7a64323d87d452a5a27c79dad85ed2daab647f6c0f0105826cR59-R61 is breaking redirects, somehow, and I've love to dig into the whole "why".

2021-09-02 21:16 UTC, Pomax commented
Right, found the problem here: `privacynotincluded/products/blah` would fail because the products.py code was directly referencing the `relocalized_url` template tag, instead of calling the "non-template-tag-code" that should have backed `relocalized_url`, so e31c7a1bfce8bfb1c25cff03b9e6d8adf206cff1 fixes that.

2021-09-02 21:17 UTC, Pomax commented on network-api/networkapi/wagtailpages/templatetags/localization.py
> +
```suggestion
# Force-relocalize a URL
@register.simple_tag(takes_context=True)
def relocalized_url(context, url):
    request = context['request']
    locale_code = get_language_from_request(request, True)
    return relocalize_url(url, locale_code)


```

2021-09-02 21:40 UTC, Pomax commented
@TheoChevalier @KalobTaulien one last pass: tests pass now, and I'm pretty sure we're good to go now, but just in case I had a typo in that last commit =D

2021-09-03 12:00 UTC, TheoChevalier approved these changes
Thanks for digging that! Looking good

2021-09-07 16:50 UTC, merged