Localize categories
mozilla/foundation.mozilla.org pull request #7237
Opened 2021-08-18 20:56 UTC by Pomax

Closes https://github.com/mozilla/foundation.mozilla.org/issues/7122

Builds on https://github.com/mozilla/foundation.mozilla.org/pull/7236

This fix introduces a new templating tag `localized_version` which can be used with anything that supports the `.get_translation(locale)` function, with template updates that use this tag to make sure there's a handle to the URL-correct localized category, for showing users category names in their own language.

2021-08-19 16:06 UTC, TheoChevalier requested changes
A couple templates are broken due to the tag not being loaded, but otherwise it works well!

Now realizing my comment on the other PR about this link not being localized probably belongs to this one instead.
<img width="839" alt="Capture d’écran 2021-08-19 à 17 57 27" src="https://user-images.githubusercontent.com/1294206/130103309-1c4acf47-2634-41c2-90ed-22a89b06803f.png">

2021-08-30 09:17 UTC, TheoChevalier requested changes
It’s better if I *actually* submit my review comment… (using `localizedroutablepageurl` to localize the links in cards)

2021-08-31 10:30 UTC, TheoChevalier reviewed
Just found one `.localized` missing, but otherwise looks good!

2021-08-31 10:30 UTC, TheoChevalier commented on network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/blog_authors.html
> +      | <a class="category" href="{{blog_index.url}}category/{{category.slug}}">{{ localized_category }}</a>
```suggestion
      | <a class="category" href="{{blog_index.localized.url}}category/{{category.slug}}">{{ localized_category }}</a>
```

2021-08-31 22:29 UTC, Pomax commented
suggestion merged =D

2021-09-01 16:57 UTC, TheoChevalier approved these changes
Thanks! Looks like everything is working :)

2021-09-02 21:41 UTC, Pomax commented
marking as blocked until 7236 is merged in.

2021-09-09 19:46 UTC, KalobTaulien approved these changes

2021-09-22 11:34 UTC, TheoChevalier approved these changes
R+ with just a suggestion to merge

2021-09-22 14:03 UTC, TheoChevalier requested changes
Actually, did additional testing and it seems there’s been a regression along the way 😟

With a localize Advocacy snippet, I can’t get http://localhost:8000/fr/blog/category/advocacy/ to show a localized name + intro on the page, instead it’s available at http://localhost:8000/fr/blog/category/militantisme/ which shouldn’t even be a valid URL.

I’m pretty sure a previous version of this PR had the correct behavior?

2021-09-22 18:33 UTC, Pomax commented
This should be all the things now: the `index` and `blog_index` have been updated so that their links and content are pulled from the current locale, whatever that may be, and some of the templates have been updated because they had a hardcoded `/blog` and making it explicitly localized felt future-proofy.

2021-09-23 12:34 UTC, TheoChevalier requested changes
Getting cloooooooose 🤞

Unfortunately it’s crashing when opening a category that is not translated:
<img width="822" alt="Capture d’écran 2021-09-23 à 14 28 56" src="https://user-images.githubusercontent.com/1294206/134507232-ef930c19-c30c-465b-b61e-e5cac9240544.png">

Also noticed translated slugs are still valid URLs http://localhost:8000/fr/blog/category/militantisme/, but this can be fixed in a follow up

2021-09-23 15:45 UTC, Pomax commented
This should finally do it...? 🤞

2021-09-23 15:50 UTC, TheoChevalier approved these changes
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

2021-09-23 15:56 UTC, merged