updated publication and blog pages to work with get_page_authors tag
mozilla/foundation.mozilla.org pull request #7334
Opened 2021-09-07 22:10 UTC by danielfmiranda

Closes #7333 

**Link to sample test page**:

## Checklist

**Changes in Models:**
- [x] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations)

2021-09-07 22:55 UTC, danielfmiranda commented on network-api/networkapi/wagtailpages/templatetags/homepage_tags.py
> +def get_page_authors(parent_page):
It appears that this function already existed to return the authors of a blog page, I have updated it to accept both blog pages and publication pages, that way we can continue to use the single "author-images" template by calling this tag in both the blog page template and publication page template

2021-09-08 18:34 UTC, Pomax requested changes

2021-09-08 18:34 UTC, Pomax commented on network-api/networkapi/wagtailpages/templatetags/homepage_tags.py
> +def get_page_authors(parent_page):
let's not call this "parent_page" though, this is still just `page`
```suggestion
def get_page_authors(page):
```

2021-09-08 18:34 UTC, Pomax commented on network-api/networkapi/wagtailpages/templates/wagtailpages/publication_page.html
> +  {% include "./fragments/publication_hero.html" with  parent_page=page download_file=page.publication_file is_publication_page=page.is_publication_page %}
```suggestion
  {% include "./fragments/publication_hero.html" with  page=page download_file=page.publication_file is_publication_page=page.is_publication_page %}
```

2021-09-08 18:34 UTC, Pomax commented on network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/publication_hero.html
> +{% get_page_authors parent_page as authors %}
```suggestion
{% get_page_authors page as authors %}
```

2021-09-08 21:50 UTC, danielfmiranda commented
Hi @Pomax! Thanks for your feedback, I have added the suggested changes, to update "parent_page" to "page" and have re-requested review. Thanks!

2021-09-09 17:36 UTC, Pomax approved these changes

2021-09-09 17:36 UTC, merged