Fix/7625 product share info
mozilla/foundation.mozilla.org pull request #7773
Opened 2021-11-04 17:14 UTC by richbrennan

Closes #
Related PRs/issues #

**Link to sample test page**:

## Checklist

_Remove unnecessary checks_

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

2021-11-04 18:03 UTC, richbrennan commented on network-api/networkapi/wagtailpages/templates/buyersguide/product_page.html
> -{% block head_extra %}
This block doesn't seem to exist anywhere else in the codebase.

2021-11-04 18:03 UTC, richbrennan commented on network-api/networkapi/wagtailpages/templates/buyersguide/product_page.html
> -{% block social_image %}
This block doesn't seem to exist anywhere else in the codebase.

2021-11-04 18:04 UTC, richbrennan commented on network-api/networkapi/wagtailpages/templates/buyersguide/product_page.html
> +{% block social_metadata %}
Overridden to remove extra `og:title`

2021-11-04 18:12 UTC, richbrennan commented on network-api/networkapi/wagtailpages/pagemodels/products.py
> +        return super().get_meta_description()
The parent classes method also runs
```if self.search_description:
        return self.search_description
```
But the small repetition seemed better than copying the code

2021-11-04 18:17 UTC, danielfmiranda commented
Hi everyone, just wanted to mention that this seems to be working correctly:

Here is what the PNI product page would look like on twitter:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/18314510/140396691-0904e866-22d5-450b-a57c-061d603c2ca3.png">

and in slack:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/18314510/140396839-914bccd1-19a6-41f7-9d9c-53977179a1aa.png">

2021-11-04 19:36 UTC, kristinashu commented
Thank you for the screen caps Daniel! This is looking good - seems like it's pulling the title, intro text, and image correctly.

Anyone know why Slack is showing "Foundation Home Page"?

Blog pages in Slack say "Mozilla Foundation" which seems better than "Foundation Home Page".

<img width="603" alt="image" src="https://user-images.githubusercontent.com/1068783/140407684-5d12710e-6d96-4cf8-bfc2-06ce748d2e67.png">

2021-11-05 16:27 UTC, kristinashu approved these changes
Awesome, thank you Rich!

2021-11-05 17:01 UTC, TheoChevalier requested changes

2021-11-08 19:14 UTC, TheoChevalier approved these changes
L10n r+!

2021-11-08 23:08 UTC, Pomax requested changes
Is there a way we can use https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/mixin/foundation_metadata.py here?

2021-11-09 15:29 UTC, richbrennan commented
> Is there a way we can use https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/mixin/foundation_metadata.py here instead?

I'm not sure I follow, as I kind of am using the mixin by adding/overriding the methods defined by the `wagtail-metadata` package as required for the page. I'd be reluctant to try and shoehorn my page-specific logic into the `FoundationMetadataPageMixin` class, keeping it on the page itself seems most appropriate given it only applies to product pages, or have I missed something?

2021-11-10 18:28 UTC, Pomax commented
I've filed https://github.com/mozilla/foundation.mozilla.org/issues/7828 to look at whether we can consolidate and delegate metadata, so we can look at that separately from this specific PR

2021-11-10 18:28 UTC, Pomax requested changes
R+ given https://github.com/mozilla/foundation.mozilla.org/issues/7828, but it looks like there's a merge conflict that needs fixing before we can land this.

2021-11-11 12:05 UTC, richbrennan commented
Gah, broken by my own other ticket. Have fixed and pushed

2021-11-15 16:57 UTC, Pomax approved these changes

2021-11-15 16:57 UTC, merged