[7735] override wagtail-metadata template to exclude meta title
mozilla/foundation.mozilla.org pull request #7816
Opened 2021-11-09 16:59 UTC by richbrennan

Closes #7735

**Link to sample test page**:

2021-11-09 17:18 UTC, Pomax requested changes
tiny change + a question

2021-11-10 11:53 UTC, richbrennan commented on network-api/networkapi/templates/wagtailmetadata/parts/tags.html
> +
Done!

2021-11-10 11:58 UTC, richbrennan commented on .gitignore
> +parts/*
No, without the `*` it doesn't even read `parts/` in order to be able to add `tags.html` back in https://stackoverflow.com/a/2820310

2021-11-10 12:00 UTC, richbrennan commented on .gitignore
> +parts/*
No, without the `*` it doesn't read the contents of `parts/` to be able to add `tags.html` back in https://stackoverflow.com/a/2820310

2021-11-15 18:09 UTC, Pomax approved these changes

2021-11-15 18:34 UTC, merged