now scrolling to section after being pushed down by new data
mozilla/foundation.mozilla.org pull request #7990
Opened 2021-12-07 00:32 UTC by danielfmiranda

Closes #7069

2021-12-07 00:56 UTC, danielfmiranda commented
Hi @Pomax I am having a little bit of trouble getting the pulse entries to load and was wondering if you could help lead me in the right direction. I believe this is a cors issue because that is whats being returned in the log: 
<img width="500" alt="image" src="https://user-images.githubusercontent.com/18314510/144946332-1933400d-c35e-4cad-8daf-f870fef23f1b.png">


However after looking at the env variables on heroku it looks like CORS is set to "*". I was wondering if you might know a way to resolve this so I can test with data? Thanks in advance!

2021-12-09 23:45 UTC, Pomax requested changes

2021-12-09 23:45 UTC, Pomax commented on source/js/components/pulse-project-list/pulse-project-list.jsx
> +    const linkedPulseObject = document.getElementById(idOfLinkedPulseObject);
Note that fragment ids are literally their own query selector, so we can just do this:
```suggestion
    const linkedPulseObject = document.querySelector(window.location.hash);
```

2021-12-09 23:45 UTC, Pomax commented on source/js/components/pulse-project-list/pulse-project-list.jsx
> +    linkedPulseObject.scrollIntoView()
and then let's make sure to only scroll into view if there _was_ an element =)

```suggestion
    linkedPulseObject?.scrollIntoView()
```

2021-12-10 00:34 UTC, Pomax approved these changes
lgtm!

2021-12-10 00:34 UTC, merged