[WIP] replace cypress with playwright
mozilla/foundation.mozilla.org pull request #7999
Opened 2021-12-09 19:21 UTC by Pomax

do not merge.

Closes #7711

2021-12-09 21:01 UTC, Pomax commented on tests/wait-for-images.js
> +        const visible = Array.from(imgs).filter(i => i.offsetParent !== null)
If an element isn't visible due to `display:none` anywhere on it or its ancestors, `e.offsetParent` will be null

2021-12-09 23:35 UTC, danielfmiranda approved these changes
Hi Pomax, thanks for providing easy-to-follow instructions. 

Everything seems to be working as expected on my local machine, and when I look at the CI tests I see there are mentions of playwright. 

Approving!

2021-12-10 03:49 UTC, fessehaye requested changes
```
$ npm run playwright:urls

> playwright:urls
> wait-on -i 3000 http://localhost:8000/cms && playwright test ./tests/urls.spec.js     

Using config at C:\Users\Simon\Documents\GitHub\foundation.mozilla.org\playwright.config.js
ReferenceError: FoundationURLs is not defined
```

looks like it is missing an import?

2021-12-13 17:15 UTC, Pomax commented
@fessehaye indeed, looks like the url file was missing the fomo and mozfest URL imports - updated =D

2021-12-13 18:43 UTC, fessehaye approved these changes
Thanks for the update!

2021-12-13 21:15 UTC, merged