file is now a .pdf instead of .txt
mozilla/foundation.mozilla.org pull request #8128
Opened 2022-01-20 03:02 UTC by danielfmiranda

Closes #6414

2022-01-20 19:57 UTC, danielfmiranda commented
HI @Pomax! Thank you for taking the time to review this ticket, I have a quick question about the requirements to call this complete:

If you follow the testing steps above, you will note that the file is now a PDF, however, when clicked on the PDF is empty. 

I wanted to bring up that before this change was made, the "Download PDF" button generated a .txt file that was also empty and unable to be opened when downloaded.

When trying out the different media types found here https://faker.readthedocs.io/en/master/providers/faker.providers.file.html#faker.providers.file.Provider I also noted that all of the different files generated by faker (mp3/move/mp4/img) were 0 bytes as well. 

Just wanted to double check that this change would be enough to call the ticket "complete" as the file type is changed. When looking into populating the PDF, there seems to be no mention of that in the documentation for faker or any support online as well, which Kalob seems to have mentioned when he gave this ticket a try as well here: https://github.com/mozilla/foundation.mozilla.org/issues/6414

Thanks!

2022-01-24 18:14 UTC, Pomax requested changes

2022-01-24 18:14 UTC, Pomax commented on network-api/networkapi/wagtailpages/factory/publication.py
> +        filename=Faker('file_name', category='image', extension='pdf')
Also, shouldn't this be `category='document'`?

2022-01-27 19:33 UTC, danielfmiranda commented on network-api/networkapi/wagtailpages/factory/publication.py
> +        filename=Faker('file_name', category='image', extension='pdf')
Hi @Pomax! i have updated the file to now be a valid PDF like discussed and have re-requested review.
Thanks!

2022-01-27 20:39 UTC, Pomax approved these changes

2022-01-27 20:39 UTC, merged