Feature/8310 research detail page
mozilla/foundation.mozilla.org pull request #8448
Opened 2022-03-15 19:10 UTC by tbrlpld

Closes #8310 
Related PRs/issues #

**Link to sample test page**:

## Checklist

_Remove unnecessary checks_

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

2022-03-15 22:13 UTC, tbrlpld commented
@danielfmiranda I realize you are probably not familiar with the Research Hub work so far, but I am requesting review from you only in case @Pomax won't be able to review this week.

2022-03-21 18:32 UTC, Pomax commented on network-api/networkapi/utility/faker/helpers.py
> +    Return randnom objects up to a maximum number.
```suggestion
    Return random objects up to a maximum number.
```

2022-03-21 19:45 UTC, Pomax requested changes

2022-03-21 21:19 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/factory/documents.py
> +# https://github.com/mvantellingen/wagtail-factories/blob/master/src/wagtail_factories/factories.py
I only moved this from the original local with the rest of the document factory, so I am actually not even familiar what this refers to 😅 

I'll try to see what I can find.

2022-03-21 21:29 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/pagemodels/research_hub/detail_page.py
> +    ]
We could make it explicit, but char and text fields translatable automatically.

https://www.wagtail-localize.org/how-to/field-configuration/

2022-03-22 21:44 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/factory/documents.py
> +        data=b'''
Not sure what this was supposed to do, but the generated "files" where no valid PDFs. I have completely removed this now. Documents can still be generated, but I am not specifying any data anymore. This did have no impact on the functionality.

2022-03-22 21:45 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/pagemodels/research_hub/detail_page.py
> +from networkapi.wagtailpages.pagemodels.customblocks import base_rich_text_options
Yea, I was using that because I am following "module level imports". But yea, in this case it was a little ridiculous.

2022-03-22 22:28 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/pagemodels/research_hub/detail_page.py
> +    ]
I have made this explicit now.

2022-03-23 15:55 UTC, tbrlpld commented
@Pomax I have addressed your feedback

2022-03-29 17:41 UTC, Pomax requested changes
this looks good, but the migration will have to be renumbered before we can land this

2022-03-29 19:39 UTC, tbrlpld commented
@Pomax the migrations are renumbered now 👍

2022-03-29 19:44 UTC, Pomax approved these changes

2022-03-29 19:45 UTC, merged