Research detail page (unfinished, but close)
mozilla/foundation.mozilla.org pull request #8624
Opened 2022-05-04 03:50 UTC by KalobTaulien

Ticket #8387 

This is still a WIP but it's _mostly_ done. A couple TODO's in the template comments. 

The cover_image needs to be the main image (not the hero image), but I wasn't able to get to that today. 

I can pick this back up on Monday or if someone is feeling adventurous they can take what I have and carry it over the finish line.

2022-05-04 17:19 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/templates/wagtailpages/research_detail_page.html
> +        {% image page.image fill-259x344 as img %}
Probably best done with a method on the page to retrieve the parent (library) banner image.

2022-05-09 18:26 UTC, KalobTaulien commented on network-api/networkapi/wagtailpages/templates/wagtailpages/research_detail_page.html
> +                {% endif %}
Ah I see that now. We need the author_image in the template too (for the research authors). But Ill apply this to the related topics section right away.

2022-05-09 18:36 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/templates/wagtailpages/research_detail_page.html
> +                {% endif %}
Yea, I see. My comment was mostly meant for the metadata section below the heading.

2022-05-09 18:44 UTC, KalobTaulien commented
@tbrlpld Fixed up everything you found to the exception of the `research_authors` because we need the author images (if they one have one) and the author name. Wasn't sure if you were working on that or if you'd mind if I stepped in and added that, so I left it as is for now.

2022-05-11 21:21 UTC, tbrlpld requested changes
@KalobTaulien thanks for working on this. 

There are a few lines that need consideration, partly because of overlapping work. 

A few other points that are not code comments that I noticed while running your branch locally: 

- [ ] On mobile, the other of cover image and the heading section is inverted. The heading should come above the cover image. 
- [ ] The little header image nook on the right is missing on mobile and tablet sizes
- [ ] The metadata style does not seem to match the design. I get some strange border on the left and top. You can probably have a look at the detail card fragment if you are interested in a reference implementation of very similar styling. 
- [ ] The author names should link to the respective author detail page. I have updated the acceptance criteria to make this explicit. 
- [ ] The tablet layout had been added to the designs. We should update the implementation to reflect that. 
- [ ] On desktop, the heading section should be only as wide as the "overview" section. Currently it takes the whole width of the cut out.

2022-05-18 21:03 UTC, tbrlpld commented
@KalobTaulien Don't worry about the nook in the banner image. I am moving this to the base template, because it's the same on all research hub pages except the landing page.

2022-05-20 21:33 UTC, tbrlpld commented
Closing this in favour of #8730 8730

2022-05-20 21:33 UTC, closed without merging