YouTube Regrets 2022 - Localization fixes
mozilla/foundation.mozilla.org pull request #9353
Opened 2022-09-12 12:10 UTC by TheoChevalier

- Localizing video titles in the timeline
- Further l10n fixes in other area of the page

2022-09-13 22:06 UTC, tbrlpld requested changes
@TheoChevalier I have left some questions, that would be good to clarify.

2022-09-13 22:06 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2022/fragments/timeline.html
> +        {% include './video-thumb.html' with class="tw-col-span-6 tw-col-start-2 tw-row-start-4" image='scene4/4.jpg' speed="3" text=localized_title_4_4 %}
**Question** Is there a particular reason we are not having the variable definition and it's use closer together? (trans, include, trans, include, ...)

2022-09-13 22:06 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2022/fragments/timeline.html
> +        {% include './video-thumb.html' with class="tw-col-span-6 tw-col-start-2 tw-row-start-3" image='scene4/7.jpg' speed="6" text=localized_title_4_7 %}
See above

2022-09-13 22:06 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2022/fragments/timeline.html
> +        {% include './video-thumb.html' with class="tw-col-span-6 tw-col-start-2 tw-row-start-8" image='scene5/16.jpg' speed="3" text=localized_title_5_16 %}
See above

2022-09-13 22:06 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2022/fragments/timeline.html
> +        {% include './video-thumb.html' with class="tw-col-span-6 tw-col-start-2 medium:tw-col-start-3 tw-row-start-7" image='scene5/20.jpg' speed="3" text=localized_title_5_20 %}
See above

2022-09-13 22:06 UTC, tbrlpld commented on network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2022/fragments/timeline.html
> +        {% include './video-thumb.html' with class="tw-col-span-6 tw-col-start-1 tw-row-start-12" size="small" image='scene6/3.jpg' speed="3" text=localized_title_6_3 %}
See above

2022-09-14 14:00 UTC, TheoChevalier commented
> @TheoChevalier I have left some questions, that would be good to clarify.

Hey @tbrlpld , there was no specific reason for that, I debated this with myself and didn’t have a strong opinion, I just through grouping them would be more readable overall.
Just pushed an update!

2022-09-14 18:29 UTC, tbrlpld approved these changes

2022-09-14 18:30 UTC, tbrlpld commented
> > @TheoChevalier I have left some questions, that would be good to clarify.
> 
> Hey @tbrlpld , there was no specific reason for that, I debated this with myself and didn’t have a strong opinion, I just thought grouping them would be more readable overall. Just pushed an update!

Thanks @TheoChevalier for the clarification. I think this way is a little easier to grasp. Thanks for the update.

2022-09-15 11:08 UTC, merged