added bg-cta to homepage
mozilla/foundation.mozilla.org pull request #9407
Opened 2022-09-20 19:16 UTC by danielfmiranda

# Description

Link to sample test page:
Related PRs/issues: #9357

# Checklist

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

2022-09-20 20:14 UTC, danielfmiranda commented on network-api/networkapi/templates/pages/buyersguide/home.html
> +              <div class="{{row_item_classes}} large:-tw-mt-[20px]">
this negative margin makes sure that the callout box is top-lined with the rest of the items, as shown in the figma comp!

2022-09-21 05:56 UTC, fessehaye requested changes
Alignment is off for desktop, I think removing the negative margin would be more accurate

2022-09-21 17:14 UTC, danielfmiranda commented
Thanks @fessehaye! Updated

2022-09-21 21:01 UTC, fessehaye approved these changes
thanks daniel!

2022-09-22 01:57 UTC, merged