updated links to donate site to instead render fru modal
mozilla/foundation.mozilla.org pull request #9858
Opened 2022-12-15 21:51 UTC by danielfmiranda

# Description

Link to sample test page:
Related PRs/issues: #9856

2022-12-15 22:21 UTC, danielfmiranda commented on network-api/networkapi/wagtailpages/templates/wagtailpages/pages/dear_internet_page.html
> +        {% if page.cta_button_text %}
Like mentioned, we dont want this to link anywhere externally but instead push the relative url `?form=donate` so we can render the fundraise up modal

2022-12-15 22:35 UTC, mtdenton requested changes

2022-12-15 22:35 UTC, mtdenton commented on source/js/components/petition/donation-modal.jsx
>            `utm_source=foundation.mozilla.org`,
Let's go ahead and drop these UTMs.

2022-12-15 22:41 UTC, danielfmiranda commented on source/js/components/petition/donation-modal.jsx
>            `utm_source=foundation.mozilla.org`,
Done!

2022-12-15 22:44 UTC, mtdenton approved these changes

2022-12-16 00:05 UTC, mmmavis approved these changes

2022-12-16 00:12 UTC, merged